INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("10", "envelopes", "1", "Envelopes", NULL, 10, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("20", "envelopes", "2", "Shop by Size", NULL, 20, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("30", "envelopes", "3", "Business Envelopes", "https://www.envelopes.com/envelopes/control/category?af=use:business&sort=MOST_POPULAR", 30, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("40", "envelopes", "4", "#10 (4 1/8 x 9 1/2)", "https://www.envelopes.com/10-envelopes", 40, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("50", "envelopes", "4", "#9 (3 7/8 x 8 7/8)", "https://www.envelopes.com/9-envelopes", 50, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("60", "envelopes", "4", "#6 3/4 (3 5/8 x 6 1/2)", "https://www.envelopes.com/invitations/square-flap-envelopes?af=si:358x612%20prodtype:products&sort=SIZE_SMALL", 60, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("70", "envelopes", "4", "6 x 9", "https://www.envelopes.com/6-x-9-envelopes", 70, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("80", "envelopes", "4", "9 x 12", "https://www.envelopes.com/9-x-12-envelopes", 80, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("90", "envelopes", "4", "10 x 13", "https://www.envelopes.com/10-x-13-envelopes", 90, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("100", "envelopes", "5", "All Business Envelopes", "https://www.envelopes.com/envelopes/control/category?af=use:business&sort=MOST_POPULAR", 100, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("110", "envelopes", "3", "Invitation Envelopes", "https://www.envelopes.com/envelopes/control/category?af=use:invitation&sort=MOST_POPULAR", 110, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("120", "envelopes", "4", "A1 (3 5/8 x 5 1/8)", "https://www.envelopes.com/envelopes/control/category?af=si:358x518%20st:squareflap%20st:contourflap", 120, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("130", "envelopes", "4", "A2 (4 3/8 x 5 3/4)", "https://www.envelopes.com/envelopes/control/category?af=si:438x534%20st:squareflap%20st:contourflap", 130, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("140", "envelopes", "4", "A4 (4 1/4 x 6 1/4)", "https://www.envelopes.com/envelopes/control/category?af=si:414x614%20st:squareflap%20st:contourflap", 140, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("150", "envelopes", "4", "A6 (4 3/4 x 6 1/2)", "https://www.envelopes.com/envelopes/control/category?af=si:434x612%20st:squareflap%20st:contourflap", 150, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("160", "envelopes", "4", "A7 (5 1/4 x 7 1/4)", "https://www.envelopes.com/a7-envelopes", 160, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("170", "envelopes", "4", "A8 (5 1/2 x 8 1/8)", "https://www.envelopes.com/a8-envelopes", 170, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("180", "envelopes", "4", "A9 (5 3/4 x 8 3/4)", "https://www.envelopes.com/a9-envelopes", 180, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("190", "envelopes", "4", "A10 (6 x 9 1/2)", "https://www.envelopes.com/envelopes/control/category?af=si:6x912&sort=MOST_POPULAR", 190, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("200", "envelopes", "5", "All Invitation Envelopes", "https://www.envelopes.com/envelopes/control/category?af=use:invitation&sort=MOST_POPULAR", 200, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("210", "envelopes", "3", "Mini Envelopes", "https://www.envelopes.com/mini-envelopes", 210, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("220", "envelopes", "4", "Credit Card Sleeves (2 3/8 x 3 1/2)", "https://www.envelopes.com/envelopes/control/search?w=credit+card+sleeve&c=0", 220, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("230", "envelopes", "4", "#17 Mini (2 11/16 x 3 11/16)", "https://www.envelopes.com/envelopes/control/category?af=si:21116x31116", 230, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("240", "envelopes", "4", "#00 Coin (1 11/16 x 2 3/4)", "https://www.envelopes.com/envelopes/control/category?af=si:11116x234%20prodtype:products", 240, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("250", "envelopes", "4", "#1 Coin (2 1/4 x 3 1/2)", "https://www.envelopes.com/envelopes/control/category?af=si:214x312", 250, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("260", "envelopes", "4", "#3 Coin (2 1/2 x 4 1/4)", "https://www.envelopes.com/envelopes/control/category?af=si:212x414", 260, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("270", "envelopes", "4", "#4 Coin (3 x 4 1/2)", "https://www.envelopes.com/envelopes/control/category?af=si:3x412", 270, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("280", "envelopes", "4", "#5 1/2 Coin (3 1/8 x 5 1/2)", "https://www.envelopes.com/envelopes/control/category?af=si:318x512", 280, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("290", "envelopes", "4", "#7 Coin (3 1/2 x 6 1/2)", "https://www.envelopes.com/envelopes/control/category?af=si:312x612", 290, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("300", "envelopes", "5", "All Mini Envelopes", "https://www.envelopes.com/mini-envelopes", 300, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("310", "envelopes", "3", "Square Envelopes", "https://www.envelopes.com/envelopes/control/category?af=st:square%20prodtype:products&sort=SIZE_SMALL", 310, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("320", "envelopes", "4", "3 1/4 x 3 1/4", "https://www.envelopes.com/envelopes/control/category?af=si:314x314", 320, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("330", "envelopes", "4", "4 x 4", "https://www.envelopes.com/envelopes/control/category?af=si:4x4", 330, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("340", "envelopes", "4", "5 x 5", "https://www.envelopes.com/envelopes/control/category?af=si:5x5", 340, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("350", "envelopes", "4", "6 x 6", "https://www.envelopes.com/envelopes/control/category?af=si:6x6", 350, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("360", "envelopes", "4", "7 x 7", "https://www.envelopes.com/envelopes/control/category?af=si:7x7", 360, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("370", "envelopes", "4", "8 x 8", "https://www.envelopes.com/envelopes/control/category?af=si:8x8", 370, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("380", "envelopes", "4", "9 x 9", "https://www.envelopes.com/envelopes/control/category?af=si:9x9", 380, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("390", "envelopes", "4", "12 1/2 x 12 1/2", "https://www.envelopes.com/envelopes/control/category?af=si:1212x1212", 390, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("400", "envelopes", "5", "All Square Envelopes", "https://www.envelopes.com/envelopes/control/category?af=st:square%20prodtype:products&sort=SIZE_SMALL", 400, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("410", "envelopes", "2", "Shop by Category", NULL, 410, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("420", "envelopes", "3", "Business Envelopes", "https://www.envelopes.com/business-envelopes", 420, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("430", "envelopes", "4", "Regular Envelopes", "https://www.envelopes.com/business/regular-envelopes", 430, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("440", "envelopes", "4", "Window Envelopes", "https://www.envelopes.com/business/window-envelopes", 440, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("450", "envelopes", "4", "Peel & Press Envelopes", "https://www.envelopes.com/envelopes/control/search?af=sm:peelpress&w=peel%20&%20press&c=0", 450, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("460", "envelopes", "4", "Square Flap Envelopes", "https://www.envelopes.com/invitations/square-flap-envelopes", 460, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("470", "envelopes", "4", "Booklet Envelopes", "https://www.envelopes.com/business/booklet-envelopes", 470, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("480", "envelopes", "4", "Open End Envelopes", "https://www.envelopes.com/business/open-end-envelopes", 480, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("490", "envelopes", "4", "Clasp Envelopes", "https://www.envelopes.com/business/clasp-envelopes", 490, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("500", "envelopes", "4", "Remittance Envelopes", "https://www.envelopes.com/business/remittance-envelopes", 500, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("510", "envelopes", "4", "Coin Envelopes", "https://www.envelopes.com/coin-envelopes", 510, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("520", "envelopes", "4", "Jumbo Envelopes", "https://www.envelopes.com/envelopes/control/search?w=Jumbo+Envelopes", 520, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("530", "envelopes", "4", "Expansion Envelopes", "https://www.envelopes.com/shipping/expansion-envelopes", 530, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("540", "envelopes", "4", "Paperboard Mailers", "https://www.envelopes.com/shipping/paperboard-mailers-envelopes", 540, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("550", "envelopes", "4", "Tyvek Envelopes", "https://www.envelopes.com/shipping/tyvek", 550, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("560", "envelopes", "5", "All Business Envelopes", "https://www.envelopes.com/business-envelopes", 560, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("570", "envelopes", "3", "Invitation Envelopes", "https://www.envelopes.com/invitation-envelopes", 570, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("580", "envelopes", "4", "Square Flap Envelopes", "https://www.envelopes.com/invitations/square-flap-envelopes", 580, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("590", "envelopes", "4", "Contour Flap Envelopes", "https://www.envelopes.com/invitations/contour-flap-envelopes", 590, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("600", "envelopes", "4", "Pointed Flap Envelopes", "https://www.envelopes.com/invitations/pointed-flap-envelopes", 600, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("610", "envelopes", "4", "Lined Envelopes", "https://www.envelopes.com/invitations/lined-envelopes", 610, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("620", "envelopes", "4", "Square Envelopes", "https://www.envelopes.com/invitations/square-envelopes", 620, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("630", "envelopes", "4", "Mini Envelopes", "https://www.envelopes.com/mini-envelopes", 630, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("640", "envelopes", "4", "Photo Greeting Envelopes", "https://www.envelopes.com/invitation/square-flap/photo-greeting-card-envelopes", 640, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("650", "envelopes", "5", "All Invitation Envelopes", "https://www.envelopes.com/invitation-envelopes", 650, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("660", "envelopes", "3", "Specialty Envelopes", "https://www.envelopes.com/specialty-envelopes", 660, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("670", "envelopes", "4", "Airmail Envelopes", "https://www.envelopes.com/envelopes/control/search?w=Airmail+Envelopes", 670, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("680", "envelopes", "4", "First Class Envelopes", "https://www.envelopes.com/envelopes/control/search?w=First+Class+Envelopes", 680, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("690", "envelopes", "4", "Coin Envelopes", "https://www.envelopes.com/coin-envelopes", 690, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("700", "envelopes", "4", "Gift Card Envelopes", "https://www.envelopes.com/envelopes/control/search?w=Gift+Card+Envelopes", 700, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("800", "envelopes", "4", "Credit Card Sleeves", "https://www.envelopes.com/business/open-end/credit-card-sleeve-envelopes", 800, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("810", "envelopes", "4", "Currency Envelopes", "https://www.envelopes.com/invitation/square-flap/currency-envelopes", 810, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("820", "envelopes", "4", "Expansion Envelopes", "https://www.envelopes.com/shipping/expansion-envelopes", 820, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("830", "envelopes", "4", "Tyvek Envelopes", "https://www.envelopes.com/shipping/tyvek", 830, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("840", "envelopes", "4", "Conformer Envelopes", "https://www.envelopes.com/envelopes/control/search?w=conformer+envelopes", 840, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("850", "envelopes", "4", "W-2 Envelopes", "https://www.envelopes.com/envelopes/control/search?w=W-2+Envelopes", 850, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("860", "envelopes", "4", "Full Face Window Envelopes", "https://www.envelopes.com/envelopes/control/search?w=Full+Face+Window+Envelopes", 860, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("870", "envelopes", "4", "Button & String Envelopes", "https://www.envelopes.com/10-button-and-string-envelopes", 870, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("880", "envelopes", "5", "All Specialty Envelopes", "https://www.envelopes.com/specialty-envelopes", 880, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("890", "envelopes", "2", "Shop By Color", "https://www.envelopes.com/colors", 890, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("900", "envelopes", "4", "White", "https://www.envelopes.com/colors/white-envelopes", 900, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("910", "envelopes", "4", "Red", "https://www.envelopes.com/colors/red-envelopes", 910, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("920", "envelopes", "4", "Blue", "https://www.envelopes.com/colors/blue-envelopes", 920, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("930", "envelopes", "4", "Gold", "https://www.envelopes.com/colors/gold-envelopes", 930, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("940", "envelopes", "4", "Natural", "https://www.envelopes.com/colors/natural-envelopes", 940, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("950", "envelopes", "4", "Pink", "https://www.envelopes.com/colors/pink-envelopes", 950, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("960", "envelopes", "4", "Green", "https://www.envelopes.com/colors/green-envelopes", 960, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("970", "envelopes", "4", "Silver", "https://www.envelopes.com/colors/silver-envelopes", 970, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("980", "envelopes", "4", "Yellow", "https://www.envelopes.com/colors/yellow-envelopes", 980, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("990", "envelopes", "4", "Purple", "https://www.envelopes.com/colors/purple-envelopes", 990, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1010", "envelopes", "4", "Teal", "https://www.envelopes.com/colors/teal-envelopes", 1010, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1020", "envelopes", "4", "Black", "https://www.envelopes.com/colors/black-envelopes", 1020, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1030", "envelopes", "4", "Orange", "https://www.envelopes.com/colors/orange-envelopes", 1030, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1040", "envelopes", "4", "Brown", "https://www.envelopes.com/colors/brown-envelopes", 1040, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1050", "envelopes", "4", "Clear", "https://www.envelopes.com/envelopes/control/shopByColor/~category_id=CLEAR", 1050, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1060", "envelopes", "4", "Grocery Bag", "https://www.envelopes.com/envelopes/control/search?w=grocery+bag&c=0", 1060, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1070", "envelopes", "5", "All Colors", "https://www.envelopes.com/colors", 1070, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1080", "envelopes", "2", "Shop by Collection", "https://www.envelopes.com/luxpaper", 1080, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1090", "envelopes", "4", "LUXPaper", "https://www.envelopes.com/luxpaper", 1090, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1100", "envelopes", "4", "Metallics", "https://www.envelopes.com/envelopes/control/search?af=col:metallics&w=*", 1100, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1110", "envelopes", "4", "Recycled", "https://www.envelopes.com/recycled-envelopes", 1110, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1120", "envelopes", "4", "LUXFoil Lined", "https://www.envelopes.com/invitations/lined-envelopes", 1120, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1130", "envelopes", "2", "Features ", "https://www.envelopes.com/shops/holiday", 1130, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1140", "envelopes", "4", "The Holiday Shop", "https://www.envelopes.com/shops/holiday", 1140, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1150", "envelopes", "4", "The Wedding Shop", "https://www.envelopes.com/wedding-shop", 1150, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1160", "envelopes", "4", "New Arrivals", "https://www.envelopes.com/new-arrivals", 1160, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1170", "envelopes", "4", "Assorted Cardstock Packs", "http://envelopes.envelopes.com/products/holiday-envelope-and-stationery-sets", 1170, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1180", "envelopes", "4", "Envelope Size Guide", "https://www.envelopes.com/envelope-sizes", 1180, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1190", "envelopes", "4", "Swatchbook", "https://www.envelopes.com/paper/swatchbook-premium-envelopes-paper", 1190, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1200", "envelopes", "4", "Made to Order", "https://www.envelopes.com/made-to-order", 1200, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1210", "envelopes", "2", "Accessories", "https://www.envelopes.com/envelopes/control/product/~product_id=LINER-05", 1210, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1220", "envelopes", "4", "Envelope Liners", "https://www.envelopes.com/envelopes/control/product/~product_id=LINER-05", 1220, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1230", "envelopes", "4", "Labels & Seals", "https://www.envelopes.com/envelopes/control/category?af=st:labels", 1230, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1240", "envelopes", "4", "Glue Dots", NULL, 1240, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1250", "envelopes", "2", "Clearance", "https://www.envelopes.com/search?w=*&af=onsale:sale%20onsale:clearance", 1250, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1260", "envelopes", "5", "All Clearance", "https://www.envelopes.com/search?w=*&af=onsale:sale%20onsale:clearance", 1260, 6);








INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1270", "envelopes", "1", "Paper & Cardstock", NULL, 1270, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1280", "envelopes", "2", "Shop by Size", NULL, 1280, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1290", "envelopes", "3", "Paper", "https://www.envelopes.com/paper", 1290, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1300", "envelopes", "4", "8 1/2 x 11 Paper", "https://www.envelopes.com/paper/8-1-2-x-11-paper", 1300, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1310", "envelopes", "4", "8 1/2 x 14 Paper", "https://www.envelopes.com/paper/8-1-2-x-14-paper-grocery-bag", 1310, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1320", "envelopes", "4", "11 x 17 Paper", "https://www.envelopes.com/paper/11-x-17-paper-chocolate", 1320, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1330", "envelopes", "4", "12 x 12 Paper", "https://www.envelopes.com/paper/12-x-12-paper", 1330, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1340", "envelopes", "4", "12 x 18 Paper", "https://www.envelopes.com/paper/12-x-18-paper", 1340, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1350", "envelopes", "4", "13 x 19 Paper", "https://www.envelopes.com/envelopes/control/product/~category_id=CARDSTOCK/~product_id=13_X_19_CARDSTOCK", 1350, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1360", "envelopes", "5", "All Paper", "https://www.envelopes.com/paper", 1360, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1370", "envelopes", "3", "Cardstock", "https://www.envelopes.com/cardstock", 1370, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1380", "envelopes", "4", "8 1/2 x 11 Cardstock", "https://www.envelopes.com/cardstock/8-1-2-x-11-cardstock", 1380, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1390", "envelopes", "4", "8 1/2 x 14 Cardstock", "https://www.envelopes.com/cardstock/8-1-2-x-14-cardstock-grocery-bag", 1390, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1400", "envelopes", "4", "11 x 17 Cardstock", "https://www.envelopes.com/cardstock/11-x-17-cardstock-chocolate", 1400, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1410", "envelopes", "4", "12 x 12 Cardstock", "https://www.envelopes.com/cardstock/12-x-12-cardstock", 1410, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1420", "envelopes", "4", "12 x 18 Cardstock", "https://www.envelopes.com/envelopes/control/product/~category_id=CARDSTOCK/~product_id=12_X_18_CARDSTOCK", 1420, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1430", "envelopes", "4", "13 x 19 Cardstock", "https://www.envelopes.com/envelopes/control/product/~category_id=CARDSTOCK/~product_id=13_X_19_CARDSTOCK", 1430, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1440", "envelopes", "5", "All Cardstock", "https://www.envelopes.com/cardstock", 1440, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1450", "envelopes", "3", "Shop by Collection", "https://www.envelopes.com/envelopes/control/category/?af=use:paperandmore%20col:white", 1450, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1460", "envelopes", "4", "White", "https://www.envelopes.com/envelopes/control/category/?af=use:paperandmore%20col:white", 1460, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1470", "envelopes", "4", "Natural", "https://www.envelopes.com/envelopes/control/category/?af=use:paperandmore%20col:natural", 1470, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1480", "envelopes", "4", "Brights", "https://www.envelopes.com/envelopes/control/category/?af=use:paperandmore%20col:brights", 1480, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1490", "envelopes", "4", "Cotton", "https://www.envelopes.com/envelopes/control/category/?af=use:paperandmore%20col:cotton", 1490, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1500", "envelopes", "4", "Recycled", "https://www.envelopes.com/envelopes/control/search?w=recycled+paper", 1500, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1510", "envelopes", "4", "Metallics", "https://www.envelopes.com/envelopes/control/category/?af=use:paperandmore%20col:metallics", 1510, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1520", "envelopes", "4", "Linen", "https://www.envelopes.com/envelopes/control/category/?af=use:paperandmore%20col:linen", 1520, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1530", "envelopes", "4", "Parchment", "https://www.envelopes.com/envelopes/control/category/?af=use:paperandmore%20col:parchments", 1530, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1540", "envelopes", "5", "All Paper & Cardstock", "https://www.envelopes.com/paper-cardstock", 1540, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1550", "envelopes", "2", "Shop by Category", NULL, 1550, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1560", "envelopes", "3", "Notecards", "https://www.envelopes.com/notecards", 1560, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1570", "envelopes", "4", "Flatcards", "https://www.envelopes.com/notecards", 1570, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1580", "envelopes", "4", "Folded Cards", "https://www.envelopes.com/envelopes/control/category/~category_id=FOLDED_CARDS", 1580, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1590", "envelopes", "4", "Mini Cards", "https://www.envelopes.com/envelopes/control/search?w=mini+cards", 1590, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1600", "envelopes", "4", "Tent Cards", "https://www.envelopes.com/envelopes/control/search?w=tent+cards", 1600, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1610", "envelopes", "4", "Border Cards", "https://www.envelopes.com/envelopes/control/search?w=border+cards", 1610, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1620", "envelopes", "5", "All Notecards", "https://www.envelopes.com/notecards", 1620, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1630", "envelopes", "3", "Business Stationery", "https://www.envelopes.com/envelopes/control/search?af=use:businessstationery&w=*", 1630, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1640", "envelopes", "4", "Return Address Envelopes", "https://www.envelopes.com/envelopes/control/search?w=return+address", 1640, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1650", "envelopes", "4", "Business Letterhead", "https://www.envelopes.com/envelopes/control/search?af=st:letterhead&w=*", 1650, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1660", "envelopes", "4", "Business Cards", "https://www.envelopes.com/envelopes/control/search?af=st:businesscard&w=*", 1660, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1670", "envelopes", "4", "Business Notecards", "https://www.envelopes.com/notecards", 1670, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1680", "envelopes", "4", "Business Event Invitations", "https://www.envelopes.com/envelopes/control/search?w=Business+Event+Invitations", 1680, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1690", "envelopes", "4", "Business Thank You Cards", "https://www.envelopes.com/thank-you-cards", 1690, 3);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1700", "envelopes", "4", "Tyvek Sheets", NULL, 1700, 3);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1710", "envelopes", "4", "Certificates", NULL, 1710, 3);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1720", "envelopes", "4", "3-Hole Punched Paper", NULL, 1720, 3);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1730", "envelopes", "4", "Construction Paper", NULL, 1730, 3);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1740", "envelopes", "4", "Lined Paper", NULL, 1740, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1750", "envelopes", "5", "All Business Stationery", "https://www.envelopes.com/envelopes/control/search?af=use:businessstationery&w=*", 1750, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1760", "envelopes", "3", "Personal Stationery", "https://www.envelopes.com/envelopes/control/search?af=use:personalstationery&w=*", 1760, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1770", "envelopes", "4", "Return Address Envelopes", "https://www.envelopes.com/envelopes/control/search?w=Return+Address+Envelopes", 1770, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1780", "envelopes", "4", "Personal notecards", "https://www.envelopes.com/envelopes/control/search?&page=2&w=personal%20notecards", 1780, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1790", "envelopes", "4", "Monogrammed Notecards", "https://www.envelopes.com/envelopes/control/search?w=Monogrammed+Notecards", 1790, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1800", "envelopes", "4", "Invitations", "https://www.envelopes.com/envelopes/control/search?w=Invitations", 1800, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1810", "envelopes", "4", "Photo Greeting Cards", "https://www.envelopes.com/envelopes/control/search?w=Photo+Greeting+Cards", 1810, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1820", "envelopes", "4", "Thank You Cards", "https://www.envelopes.com/envelopes/control/search?af=use:thankyou&w=*", 1820, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1830", "envelopes", "5", "All Personal Stationery", "https://www.envelopes.com/envelopes/control/search?af=use:personalstationery&w=*", 1830, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1840", "envelopes", "2", "Features", "https://www.envelopes.com/shops/holiday", 1840, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1850", "envelopes", "4", "The Holiday Shop", "https://www.envelopes.com/shops/holiday", 1850, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1860", "envelopes", "4", "The Wedding Shop", "https://www.envelopes.com/wedding-shop", 1860, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1870", "envelopes", "4", "New Arrivals", "http://envelopes.envelopes.com/products/holiday-envelope-and-stationery-sets", 1870, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1880", "envelopes", "4", "Assorted Cardstock Packs", "https://www.envelopes.com/new-arrivals", 1880, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1890", "envelopes", "4", "Envelope Size Guide", "https://www.envelopes.com/envelope-sizes", 1890, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1900", "envelopes", "4", "Swatchbook", "https://www.envelopes.com/paper/swatchbook-premium-envelopes-paper", 1900, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1910", "envelopes", "4", "Made to Order", "https://www.envelopes.com/made-to-order", 1910, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1920", "envelopes", "3", "Accessories", "https://www.envelopes.com/envelopes/control/product/~product_id=LINER-05", 1920, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1930", "envelopes", "4", "Labels & Seals", "https://www.envelopes.com/envelopes/control/product/~product_id=LINER-05", 1930, 6);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1935", "envelopes", "4", "Gift Tags", "https://www.envelopes.com/envelopes/control/product/~product_id=LINER-05", 1935, 6);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1940", "envelopes", "4", "Glue Dots", "https://www.envelopes.com/envelopes/control/category?af=st:labels", 1940, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1950", "envelopes", "3", "Clearance", "https://www.envelopes.com/search?w=*&af=onsale:sale%20onsale:clearance", 1950, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1960", "envelopes", "5", "All Clearance", "https://www.envelopes.com/search?w=*&af=onsale:sale%20onsale:clearance", 1960, 6);











INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1970", "envelopes", "1", "Printing", NULL, 1970, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1980", "envelopes", "2", "Print Services", NULL, 1980, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("1990", "envelopes", "4", "Custom Printing", "https://www.envelopes.com/print-services", 1990, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2000", "envelopes", "4", "Recipient Addressing", "https://www.envelopes.com/recipient-addressing", 2000, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2010", "envelopes", "4", "White Ink Printing", "https://www.envelopes.com/white-ink", 2010, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2020", "envelopes", "3", "Features", NULL, 2020, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2030", "envelopes", "4", "The Holiday Shop", "https://www.envelopes.com/shops/holiday", 2030, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2040", "envelopes", "4", "The Wedding Shop", "https://www.envelopes.com/wedding-shop", 2040, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2050", "envelopes", "4", "New Arrivals", "https://www.envelopes.com/new-arrivals", 2050, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2060", "envelopes", "4", "Envelope Size Guide", "https://www.envelopes.com/envelope-sizes", 2060, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2070", "envelopes", "4", "Swatchbook", "https://www.envelopes.com/paper/swatchbook-premium-envelopes-paper", 2070, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2080", "envelopes", "4", "Made to Order", "https://www.envelopes.com/made-to-order", 2080, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2090", "envelopes", "2", "Customizable Designs", NULL, 2090, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2100", "envelopes", "3", "Business Envelopes", NULL, 2100, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2110", "envelopes", "4", "#10 (4 1/8 x 9 1/2)", "https://www.envelopes.com/envelopes/control/search?af=prodtype:designs&w=#10 envelopes", 2110, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2120", "envelopes", "4", "Business Reply Envelopes", "https://www.envelopes.com/envelopes/control/search?af=prodtype:designs&w=Business%20Reply", 2120, 3);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2130", "envelopes", "3", "Invitation Envelopes", NULL, 2130, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2140", "envelopes", "4", "A7 (5 1/4 x 7 1/4)", "https://www.envelopes.com/envelopes/control/search?af=si:714x514%20prodtype:designs&w=*&c=0", 2140, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2150", "envelopes", "4", "A2 (4 3/8 x 5 3/4)", "https://www.envelopes.com/envelopes/control/search?af=si:438x534%20prodtype:designs&w=*&c=0", 2150, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2160", "envelopes", "4", "A1 (3 5/8 x 5 1/8)", "https://www.envelopes.com/envelopes/control/search?af=si:358x518%20prodtype:designs&w=*&c=0", 2160, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2170", "envelopes", "4", "RSVP Envelopes", "https://www.envelopes.com/envelopes/control/search?af=si:438x534%20si:358x518%20prodtype:designs&w=*&c=0", 2170, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2180", "envelopes", "3", "Remittance/Donation Envelopes", NULL, 2180, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2190", "envelopes", "4", "Donation Envelopes", "https://www.envelopes.com/envelopes/control/search?af=prodtype:designs&w=remittance%20envelopes&c=0", 2190, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2200", "envelopes", "5", "All Envelope Designs", "https://www.envelopes.com/envelopes/control/search?af=prodtype:designs&w=Envelopes", 2200, 5);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2210", "envelopes", "3", "Stationery", "https://www.envelopes.com/envelopes/control/search?af=prodtype:designs&page=5&w=stationery&c=0", 2210, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2220", "envelopes", "4", "Business Letterhead", "https://www.envelopes.com/envelopes/control/search?af=prodtype:designs&w=letterhead&c=0", 2220, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2230", "envelopes", "4", "Business Cards", "https://www.envelopes.com/envelopes/control/search?w=business+cards&c=0", 2230, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2240", "envelopes", "4", "Notecards", "https://www.envelopes.com/envelopes/control/search?af=prodtype:designs&w=notecards&c=0", 2240, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2250", "envelopes", "4", "Thank You Cards", "https://www.envelopes.com/envelopes/control/search?w=thank+you&c=0", 2250, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2260", "envelopes", "4", "Gift Certificates", "https://www.envelopes.com/envelopes/control/search?w=gift+certificates&c=0", 2260, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2270", "envelopes", "5", "All Stationery", "https://www.envelopes.com/envelopes/control/search?af=prodtype:designs&page=5&w=stationery&c=0", 2270, 6);








INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2280", "envelopes", "1", "DIY Invitations", NULL, 2280, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2290", "envelopes", "2", "Shop by Style", NULL, 2290, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2300", "envelopes", "4", "Petal Invitations", "https://www.envelopes.com/envelopes/control/search?w=Petal+Invitations", 2300, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2310", "envelopes", "4", "Pocket Invitations", "https://www.envelopes.com/envelopes/control/search?w=Pocket+Invitations", 2310, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2320", "envelopes", "4", "Flat Cards", "https://www.envelopes.com/envelopes/control/search?w=Flat+Cards", 2320, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2330", "envelopes", "4", "Folded Cards", "https://www.envelopes.com/envelopes/control/search?w=Folded+Cards", 2330, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2340", "envelopes", "4", "Square Cards", "https://www.envelopes.com/envelopes/control/search?w=Square+Cards", 2340, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2350", "envelopes", "4", "Mini Cards", "https://www.envelopes.com/envelopes/control/search?w=Mini+Cards", 2350, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2360", "envelopes", "4", "Gatefold Cards", "https://www.envelopes.com/invitations/gatefold-invitations", 2360, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2370", "envelopes", "4", "Z-Fold Cards", "https://www.envelopes.com/envelopes/control/search?w=zfold", 2370, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2380", "envelopes", "5", "See all DIY Invitations", "https://www.envelopes.com/diy-invitations", 2380, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2390", "envelopes", "2", "Features", "https://www.envelopes.com/shops/holiday", 2390, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2400", "envelopes", "4", "The Holiday Shop", "https://www.envelopes.com/shops/holiday", 2400, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2410", "envelopes", "4", "The Wedding Shop", "https://www.envelopes.com/wedding-shop", 2410, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2420", "envelopes", "4", "New Arrivals", "http://envelopes.envelopes.com/products/holiday-envelope-and-stationery-sets", 2420, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2430", "envelopes", "4", "Assorted Cardstock Packs", "https://www.envelopes.com/new-arrivals", 2430, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2440", "envelopes", "4", "Envelope Size Guide", "https://www.envelopes.com/envelope-sizes", 2440, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2450", "envelopes", "4", "Swatchbook", "https://www.envelopes.com/paper/swatchbook-premium-envelopes-paper", 2450, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2460", "envelopes", "4", "Made to Order", "https://www.envelopes.com/made-to-order", 2460, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2470", "envelopes", "2", "Accessories", "https://www.envelopes.com/envelopes/control/product/~product_id=LINER-05", 2470, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2480", "envelopes", "4", "Envelope Liners", "https://www.envelopes.com/liners", 2480, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2490", "envelopes", "4", "Labels & Seals", "https://www.envelopes.com/envelopes/control/product/~product_id=LINER-05", 2490, 6);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2500", "envelopes", "4", "Glue Dots", "https://www.envelopes.com/envelopes/control/category?af=st:labels", 2500, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2510", "envelopes", "4", "Crinkle Paper", "https://www.envelopes.com/search?w=crinkle+paper&c=0", 2510, 6);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2520", "envelopes", "4", "Gift Tags", NULL, 2520, 6);










INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2530", "envelopes", "1", "Mailroom Supplies", NULL, 2530, 1);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2540", "envelopes", "2", "Envelopes", NULL, 2540, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2550", "envelopes", "4", "Cello Envelopes", "https://www.envelopes.com/envelopes/control/search?w=Cello&c=0", 2550, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2560", "envelopes", "4", "Glassine Envelopes", "https://www.envelopes.com/envelopes/control/search?af=cog1:clear%20cog2:clear_30lbglassine&w=glassine&c=0", 2560, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2570", "envelopes", "4", "Document Envelopes", "https://www.envelopes.com/business/document-envelopes", 2570, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2580", "envelopes", "4", "Expansion Envelopes", "https://www.envelopes.com/shipping/expansion-envelopes", 2580, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2590", "envelopes", "4", "Jumbo Envelopes", "https://www.envelopes.com/envelopes/control/search?w=Jumbo+Envelopes", 2590, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2600", "envelopes", "4", "Tyvek Envelopes", "https://www.envelopes.com/shipping/tyvek", 2600, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2610", "envelopes", "4", "Pillowpak Envelopes", "https://www.envelopes.com/envelopes/control/search?w=pillowpak+envelopes", 2610, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2620", "envelopes", "4", "Tamper Evident Envelopes", "https://www.envelopes.com/envelopes/control/search?w=Tamper+Evident", 2620, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2630", "envelopes", "4", "Conformer Envelopes", "https://www.envelopes.com/envelopes/control/search?w=conformer+envelopes", 2630, 2);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2640", "envelopes", "5", "All Mailroom Envelopes", "https://www.envelopes.com/envelopes/control/category?af=use:shipping%20st:bubblelined%20st:expansion%20st:paperboardmailers%20st:specialtyuse%20st:tyvek%20st:plasticmailers%20st:luxmailers%20prodtype:products&sort=MOST_POPULAR", 2640, 2);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2650", "envelopes", "2", "Accessories", null, 2650, 4);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2660", "envelopes", "4", "Letter Openers", NULL, 2660, 4);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2670", "envelopes", "4", "Envelope Moisteners", NULL, 2670, 4);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2680", "envelopes", "4", "Fingertip Moisteners", NULL, 2680, 4);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2690", "envelopes", "4", "Rubber Finger Grips", NULL, 2690, 4);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2700", "envelopes", "4", "Colored Packing Tape", NULL, 2700, 4);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2710", "envelopes", "4", "Tape Dispensers", NULL, 2710, 4);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2720", "envelopes", "4", "Labels (Caution, Fragile)", NULL, 2720, 4);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2730", "envelopes", "5", "All Accessories", NULL, 2730, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2740", "envelopes", "2", "Mailers", NULL, 2740, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2750", "envelopes", "4", "Bubble Mailers", "https://www.envelopes.com/shipping/bubble-lined-envelopes", 2750, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2760", "envelopes", "4", "Padded Mailers", "https://www.envelopes.com/shipping/bubble-lined-envelopes", 2760, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2770", "envelopes", "4", "Plastic Mailers", "https://www.envelopes.com/shipping/plastic-mailers-envelopes", 2770, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2780", "envelopes", "4", "Paperboard Mailers", "https://www.envelopes.com/shipping/paperboard-mailers-envelopes", 2780, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2790", "envelopes", "5", "All Mailers", "https://www.envelopes.com/envelopes/control/category?af=use:shipping%20st:bubblelined%20st:expansion%20st:paperboardmailers%20st:specialtyuse%20st:tyvek%20st:plasticmailers%20st:luxmailers%20prodtype:products&sort=MOST_POPULAR", 2790, 4);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2800", "envelopes", "2", "Shipping and Packaging", NULL, 2800, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2810", "envelopes", "4", "Gift Boxes", "http://envelopes.envelopes.com/products/holiday-gift-boxes", 2810, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2840", "envelopes", "4", "Pillow Boxes", "https://www.envelopes.com/shipping/pillow-box/small-pillow-boxes-rose-quartz-metallic", 2840, 6);
INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2850", "envelopes", "4", "Mailing Tubes", "https://www.envelopes.com/mailing-tubes", 2850, 6);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2860", "envelopes", "4", "Shipping Boxes", NULL, 2860, 6);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2870", "envelopes", "4", "Corrugated Packaging", NULL, 2870, 6);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2880", "envelopes", "4", "Bubble Bags", NULL, 2880, 6);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2890", "envelopes", "4", "Polybags", NULL, 2890, 6);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2900", "envelopes", "4", "Temperature Controlled Shipping Kit", NULL, 2900, 6);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2910", "envelopes", "4", "Cold Pack", NULL, 2910, 6);
-- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2920", "envelopes", "5", "All Shipping & Packaging", NULL, 2920, 6);









--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2930", "envelopes", "1", "Desktop Supplies", NULL, 2930, 1);
---- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2940", "envelopes", "2", "Shop by Style", NULL, 2940, 2);
---- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2950", "envelopes", "4", "Planners", NULL, 2950, 2);
---- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2960", "envelopes", "4", "Notepads", NULL, 2960, 2);
---- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2970", "envelopes", "4", "Notebooks", NULL, 2970, 2);
---- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2980", "envelopes", "4", "Clipboards", NULL, 2980, 2);
---- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("2990", "envelopes", "4", "File Sorters", NULL, 2990, 2);
---- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3000", "envelopes", "4", "Desk Organizers", "", 3000, 2);
---- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3010", "envelopes", "4", "3-Hole Punchers", NULL, 3010, 2);
---- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3020", "envelopes", "4", "Staplers", NULL, 3020, 2);
---- INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3030", "envelopes", "4", "Scissors", NULL, 3030, 2);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3040", "envelopes", "2", "Presentation Folders", NULL, 3040, 2);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3050", "envelopes", "4", "9 x 12 Presentation Folders", "https://www.envelopes.com/folders/9-x-12-presentation-folders-standard-two-pocket-white-linen", 3050, 2);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3060", "envelopes", "4", "9 1/2 x 14 1/2 Presentation Folders", "https://www.envelopes.com/folders/9-1-2-x-14-1-2-presentation-folders-100lb-white", 3060, 2);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3070", "envelopes", "4", "4 x 9 Pocket Folders", "https://www.envelopes.com/folders/4-x-9-mini-folders-two-pockets-black-linen", 3070, 2);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3080", "envelopes", "4", "Hotel Key Card Holders", "https://www.envelopes.com/folders/hotel-key-card-holders-100lb-white", 3080, 2);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3090", "envelopes", "4", "Capacity Folders", "https://www.envelopes.com/folders/capacity-folders-100lb-white", 3090, 2);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3100", "envelopes", "5", "All Folders", "https://www.envelopes.com/folders", 3100, 2);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3110", "envelopes", "2", "Features", "https://www.envelopes.com/shops/holiday", 3110, 4);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3120", "envelopes", "4", "The Holiday Shop", "https://www.envelopes.com/shops/holiday", 3120, 4);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3130", "envelopes", "4", "The Wedding Shop", "https://www.envelopes.com/wedding-shop", 3130, 4);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3140", "envelopes", "4", "New Arrivals", "http://envelopes.envelopes.com/products/holiday-envelope-and-stationery-sets", 3140, 4);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3150", "envelopes", "4", "Assorted Cardstock Packs", "https://www.envelopes.com/new-arrivals", 3150, 4);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3160", "envelopes", "4", "Envelope Size Guide", "https://www.envelopes.com/envelope-sizes", 3160, 4);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3170", "envelopes", "4", "Swatchbook", "https://www.envelopes.com/paper/swatchbook-premium-envelopes-paper", 3170, 4);
--INSERT IGNORE INTO navigation_content(ID, WEB_SITE_ID, TYPE, DESCRIPTION, LINK, SEQUENCE_NUM, COLUMN_SEQUENCE_NUM) VALUES("3180", "envelopes", "4", "Made to Order", "https://www.envelopes.com/made-to-order", 3180, 4);
