import com.envelopes.util.*;

Map<String, Object> industryInfo = new HashMap<>();
Map<String, Object> productInfo = new HashMap<>();
List productList = new ArrayList<>();
Map<String, Object> browseMoreCustomInfo = new HashMap<>();
List browseMoreCustomList = new ArrayList<>();
Map<String, Object> browseMoreBlankInfo = new HashMap<>();
List browseMoreBlankList = new ArrayList<>();
Map<String, Object> params = EnvUtil.getParameterMap(request);
String industryType = (String) params.get("id");

industryInfo.put("imageName", industryType);

browseMoreCustomInfo.put("img", "SF_101_UP_5?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreCustomInfo.put("text", "Custom Presentation Folders");
browseMoreCustomInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
browseMoreCustomList.add(browseMoreCustomInfo);
browseMoreCustomInfo = new HashMap<>();
browseMoreCustomInfo.put("img", "PRB_8801_Up_Inside?fmt=png-alpha&amp;wid=180&amp;hei=185");
browseMoreCustomInfo.put("text", "Custom Binders");
browseMoreCustomInfo.put("link", "category2?categoryId=Certificate%20Holder");
browseMoreCustomList.add(browseMoreCustomInfo);
browseMoreCustomInfo = new HashMap<>();
browseMoreCustomInfo.put("img", "CHEPF_185_Up_1_WDoc?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreCustomInfo.put("text", "Custom Certificate Holders & Report Covers");
browseMoreCustomInfo.put("link", "product/~product_id=CHEL-185");
browseMoreCustomList.add(browseMoreCustomInfo);
browseMoreCustomInfo = new HashMap<>();
browseMoreCustomInfo.put("img", "hp-cardHolders?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreCustomInfo.put("text", "Custom Small Folders");
browseMoreCustomInfo.put("link", "category2?categoryId=Small%20Folder");
browseMoreCustomList.add(browseMoreCustomInfo);
browseMoreCustomInfo = new HashMap<>();
browseMoreCustomInfo.put("img", "LAW_SPOT_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreCustomInfo.put("text", "Custom Legal Folders");
browseMoreCustomInfo.put("link", "product/~product_id=LF-118");
browseMoreCustomList.add(browseMoreCustomInfo);

browseMoreBlankInfo.put("img", "SF-101_DARK_BLUE_100LB_LINEN_PERS?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreBlankInfo.put("text", "Presentation Folders");
browseMoreBlankInfo.put("link", "product/~category_id=BLANK_ST_PR_FOLDERS/~product_id=PF-DBLI");
browseMoreBlankList.add(browseMoreBlankInfo)
browseMoreBlankInfo = new HashMap<>();
browseMoreBlankInfo.put("img", "PB-2RREBLUE?fmt=png-alpha&amp;wid=180&amp;hei=185");
browseMoreBlankInfo.put("text", "Binders");
browseMoreBlankInfo.put("link", "blankProduct/~product_id=PB-2RREBLUE");
browseMoreBlankList.add(browseMoreBlankInfo);
browseMoreBlankInfo = new HashMap<>();
browseMoreBlankInfo.put("img", "CHEL-185-DDBLU100-F?fmt=png-alpha&amp;wid=130&amp;hei=185");
browseMoreBlankInfo.put("text", "Certificate Holders");
browseMoreBlankInfo.put("link", "blankProduct/~product_id=CHEL-185-DDBLK100-F");
browseMoreBlankList.add(browseMoreBlankInfo);
browseMoreBlankInfo = new HashMap<>();
browseMoreBlankInfo.put("img", "MF-144-DDP100-SMALL?fmt=png-alpha&amp;wid=180&amp;hei=185");
browseMoreBlankInfo.put("text", "Small Folders");
browseMoreBlankInfo.put("link", "product/~category_id!BLANK_SM_FOLDERS/~product_id=MF-144-DDP100");
browseMoreBlankList.add(browseMoreBlankInfo);
browseMoreBlankInfo = new HashMap<>();
browseMoreBlankInfo.put("img", "LF-118-DDBLU100?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreBlankInfo.put("text", "Legal Folders");
browseMoreBlankInfo.put("link", "product/~category_id!BLANK_LEGAL_FOLDERS/~product_id=LF-118-DDBLU100");
browseMoreBlankList.add(browseMoreBlankInfo);

if (industryType.equals("customTaxFolders")) {
	industryInfo.put("h1", "Custom Accounting and Tax Folders");
	industryInfo.put("bannerTextDesktop", "Professional CPA & tax folders for accountants and bookkeepers. Choose from a range of quality, custom print options like spot color, full color, embossing and foil stamping. Present important financial files and reports with a superior finish in our range of custom CPA folders & custom tax folders.");
	industryInfo.put("customerExamplesHeader", "Custom Tax Folder Examples");
	industryInfo.put("customerExamplesText", "Customize your tax folders with a variety of printing methods, including Full Color Printing, Spot Color, Foil Stamping, Embossing and more. See how customers in your industry are customizing their folders to stay on brand.");
	industryInfo.put("customProductHeader", "Browse More Custom Tax Folders");
	industryInfo.put("browseMoreCustomCopy", "Custom Products for your accounting firm will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("blankProductHeader", "Browse More Blank Tax Folders");
	industryInfo.put("browseBlankCopy", "Shop from our numerous blank stock products for your accounting firm.");
	industryInfo.put("customerReview", "I thought finding quality, customized folders for the firm would be a grueling process. This company made it painless and affordable for me. Would definitely recommend!");
	industryInfo.put("customerReviewName", "John Borella");
	industryInfo.put("customerReviewCompany", "Scott, Simone & Sutter Group");

	productInfo.put("id", "ACC_FOIL_1");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "3df_149_UP_1");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "PRB-8801-A-STANDING");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "ACC_EMB_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "RCSTW-191-B-STANDING");
	productInfo.put("link", "product/~category_id=BLANK_ST_PR_FOLDERS/~product_id=PF-DBLI");
	productList.add(productInfo);
	productInfo = new HashMap<>();
} else if (industryType.equals("customLegalFolders")) {
	industryInfo.put("h1", "Custom Legal Folders");
	industryInfo.put("bannerTextDesktop", "Quality pocket folders for legal firms. Customize legal folders in your preferred colors, style and texture. From tax attorneys to family lawyers, present your legal files in classic pocket folders and create a lasting impression with your clients.");
	industryInfo.put("customerExamplesHeader", "Custom Legal Folder Examples");
	industryInfo.put("customerExamplesText", "Customize your legal folders with a variety of printing methods, including Full Color Printing, Spot Color, Foil Stamping, Embossing and more. See how customers in your industry are customizing their folders to stay on brand.");
	industryInfo.put("customProductHeader", "Browse More Custom Legal Folders");
	industryInfo.put("browseMoreCustomCopy", "Custom Products for your law firm will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("blankProductHeader", "Browse More Blank Legal Folders");
	industryInfo.put("browseBlankCopy", "Shop from our numerous blank stock products for your law firm.");
	industryInfo.put("customerReview", "Excellent customer service throughout the whole process and quality legal folders with all of the printing details our firm needed. Will be ordering from here again!");
	industryInfo.put("customerReviewName", "Lynn Robertson");
	industryInfo.put("customerReviewCompany", "Law Office of Jeffrey Lebowski");
	
	productInfo.put("id", "1601-B-STANDING");
	productInfo.put("link", "product/~product_id=FL-1601");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "LAW_4CO_1");
	productInfo.put("link", "product/~category_id=LS_FOLDERS/~product_id=LF-118");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "LAW_SPOT_1");
	productInfo.put("link", "product/~category_id=LS_FOLDERS/~product_id=LF-118");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "LAW_EMB_1_D");
	productInfo.put("link", "product/~category_id=LS_FOLDERS/~product_id=LF-118");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "07564-C-STANDING");
	productInfo.put("link", "product/~product_id=FL-1601");
	productList.add(productInfo);
	productInfo = new HashMap<>();

	browseMoreCustomList.clear();
	browseMoreCustomInfo.put("img", "LAW_SPOT_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Legal Folders");
	browseMoreCustomInfo.put("link", "category?categoryId=letter");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "PRB_8801_Up_Inside?fmt=png-alpha&amp;wid=180&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Binders");
	browseMoreCustomInfo.put("link", "product/~product_id=PRB-8801");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "07564-B-STANDING?fmt=png-alpha&amp;wid=180&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Folios & Report Covers");
	browseMoreCustomInfo.put("link", "product/~product_id=CHEL-185");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "hp-cardHolders?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Small Folders");
	browseMoreCustomInfo.put("link", "product/~product_id=HF-6801");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "SF_101_UP_5?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Presentation Folders");
	browseMoreCustomInfo.put("link", "product/~product_id=LF-118");
	browseMoreCustomList.add(browseMoreCustomInfo);

	browseMoreBlankList.clear();
	browseMoreBlankInfo.put("img", "LF-118-DDBLU100?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreBlankInfo.put("text", "Legal Folders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=SF-101");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "PB-2RREBLUE?fmt=png-alpha&amp;wid=180&amp;hei=185");
	browseMoreBlankInfo.put("text", "Binders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=PB-2RREBLUE");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "EF-146_1_UP?fmt=png-alpha&amp;wid=150&amp;hei=185");
	browseMoreBlankInfo.put("text", "Folios");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=CHEL-185-DDBLK100-F");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "MF-144-DDP100-SMALL?fmt=png-alpha&amp;wid=180&amp;hei=185");
	browseMoreBlankInfo.put("text", "Small Folders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=MF-144");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "SF-101_DARK_BLUE_100LB_LINEN_PERS?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreBlankInfo.put("text", "Presentation Folders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=LF-118");
	browseMoreBlankList.add(browseMoreBlankInfo);

} else if (industryType.equals("customTitleFolders")) {
	industryInfo.put("h1", "Title and Escrow Folders");
	industryInfo.put("bannerTextDesktop", "Custom folders for escrow files and title agencies are available in a variety of styles with subtle or decorative print options. They offer effective organization of documents and smart, professional delivery when presenting clients with paperwork.");
	industryInfo.put("customerExamplesHeader", "Custom Title Agency Folder Examples");
	industryInfo.put("customerExamplesText", "Customize your title agency folders with a variety of printing methods, including Full Color Printing, Spot Color, Foil Stamping, Embossing and more. See how customers in your industry are customizing their folders to stay on brand.");
	industryInfo.put("customProductHeader", "Browse More Custom Tax Folders");
	industryInfo.put("browseMoreCustomCopy", "Custom Products for your title agency will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("blankProductHeader", "Browse More Blank Title Agency Folders");
	industryInfo.put("browseBlankCopy", "Shop from our numerous blank stock products for your title agency.");
	industryInfo.put("customerReview", "The branded escrow folders I ordered were not only very professional looking, but were also extremely affordable!");
	industryInfo.put("customerReviewName", "Will Sobchak");
	industryInfo.put("customerReviewCompany", "Cohen Brothers Agency");

	productInfo.put("id", "SF_0801_Up_3_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "LF-1401-A-STANDING");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "LF-1417-B-STANDING");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "TTL_EMB_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "3511-A-STANDING");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();

} else if (industryType.equals("customFinanceFolders")) {
	industryInfo.put("h1", "Financial Folders");
	industryInfo.put("bannerTextDesktop", "Professional custom folders for financial planners & financial advisors. Create custom finance folders with a stunning range of printing options, including full color, foil stamping and embossing. Present your financial data and contracts in classy custom folders and demonstrate the special attention-to-detail you give your clients.");
	industryInfo.put("customerExamplesHeader", "Custom Finance Folder Examples");
	industryInfo.put("customerExamplesText", "Customize your financial folders with a variety of printing methods, including Full Color Printing, Spot Color, Foil Stamping, Embossing and more. See how customers in your industry are customizing their folders to stay on brand.");
	industryInfo.put("customProductHeader", "Browse More Custom Finance Folders");
	industryInfo.put("browseMoreCustomCopy", "Custom Products for your financial firm will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("blankProductHeader", "Browse More Blank Finance Folders");
	industryInfo.put("browseBlankCopy", "Shop from our numerous blank stock products for your financial firm.");
	industryInfo.put("customerReview", "Meeting with so many clients daily, I needed really professional folders to present that were within my budget. This company was afforadable and easy to use. I received a finished product with all of the details I was looking for.");
	industryInfo.put("customerReviewName", "Jackie Bridges");
	industryInfo.put("customerReviewCompany", "Treehorn Financial");

	productInfo.put("id", "FIN_FOIL_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "VS_104_Up_1");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "FIN_SPOT_1");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "FIN_EMB_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "FJ-1603-B-SIDE-1");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();

} else if (industryType.equals("customUniversityFolders")) {
	industryInfo.put("h1", "University Folders");
	industryInfo.put("bannerTextDesktop", "Attract interest and engage students with custom college folders & custom university folders. Custom folders provide a professional presentation for student recruitment, admissions, events and more, while reinforcing your school’s brand. Available in a range of high quality print options.");
	industryInfo.put("customerExamplesHeader", "Custom University Folder Examples");
	industryInfo.put("customerExamplesText", "Custom Products for your university will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("customProductHeader", "Browse More Custom University Folders");
	industryInfo.put("browseMoreCustomCopy", "Custom Products for your university will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("blankProductHeader", "Browse More Blank University Folders");
	industryInfo.put("browseBlankCopy", "Shop from our numerous blank stock products for your University.");
	industryInfo.put("customerReview", "We purchased our folders and certificate holders from Folders.com and can't be more pleased with the experience. The customer service team was super helpful and knowledgeable about the products and what would fit our needs. Gooooo Eagles!");
	industryInfo.put("customerReviewName", "Carol Greene");
	industryInfo.put("customerReviewCompany", "Philadelphia College");

	productInfo.put("id", "SF_101_Up_2_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "RB-125-1IN-C-STANDING");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "UNI_EMB_1_D");
	productInfo.put("link", "product/~product_id=CHEL-185");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "FJ-1603-A");
	productInfo.put("link", "product/~product_id=FJ-1603");
	productList.add(productInfo);
	productInfo = new HashMap<>();

} else if (industryType.equals("customSchoolFolders")) {
	industryInfo.put("h1", "School Folders");
	industryInfo.put("bannerTextDesktop", "Inform and educate with custom school folders or custom academy folders. Ideal for keeping homework and assignments organized, and for presenting information. Personalize your folders with your school logo, colors and a range of attractive printing options, from spot color to full color, foil stamping and embossing.");
	industryInfo.put("customerExamplesHeader", "Custom School Folder Examples");
	industryInfo.put("customerExamplesText", "Customize your school folders with a variety of printing methods, including Full Color Printing, Spot Color, Foil Stamping, Embossing and more. See how customers in your industry are customizing their folders to stay on brand.");
	industryInfo.put("customProductHeader", "Browse More Custom School Folders");
	industryInfo.put("browseMoreCustomCopy", "Custom Products for your school will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("blankProductHeader", "Browse More Blank School Folders");
	industryInfo.put("browseBlankCopy", "Shop from our numerous blank stock products for your school.");
	industryInfo.put("customerReview", "Love our new school folders! The quality of the foil print is perfection!");
	industryInfo.put("customerReviewName", "Leslie Prince");
	industryInfo.put("customerReviewCompany", "Southern Bay High School");

	productInfo.put("id", "REINFORCED_FOIL_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "SF_101_Up_9");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "PPF-133-B-STANDING");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "MED_EMB_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "CM-1613-A");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();

} else if (industryType.equals("customMedicalFolders")) {
	industryInfo.put("h1", "Medical Welcome Folders");
	industryInfo.put("bannerTextDesktop", "Custom hospital folders & custom medical folders are ideal for providing patients with information, such as health brochures, care instructions, and financing plans. Choose from a range of paper stock options, styles, and textures, then add your design to stay on brand. Presenting patients and donors with custom medical folders is a great way to encourage referrals.");
	industryInfo.put("customerExamplesHeader", "Custom Medical Folder Examples");
	industryInfo.put("customerExamplesText", "Customize your medical folders with a variety of printing methods, including Full Color Printing, Spot Color, Foil Stamping, Embossing and more. See how customers in your industry are customizing their folders to stay on brand.");
	industryInfo.put("customProductHeader", "Browse More Custom Medical Folders");
	industryInfo.put("browseMoreCustomCopy", "Custom Products for your hospital will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("blankProductHeader", "Browse More Blank Medical Folders");
	industryInfo.put("browseBlankCopy", "Shop from our numerous blank stock products for your hospital.");
	industryInfo.put("customerReview", "Excellent service! We got a competitive quote for our folders, quick turnaround on the proof and free shipping! Our staff is so pleased with the new folders. ");
	industryInfo.put("customerReviewName", "Patricia Meadows");
	industryInfo.put("customerReviewCompany", "Heart & Health Medical Center");

	productInfo.put("id", "HF_6801_Up_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "PRB_8801_Up");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "PRB-8801-ECO-A-STANDING");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "MED_EMB_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "1614-A-STANDING");
	productInfo.put("link", "product/~product_id=CM-1614");
	productList.add(productInfo);
	productInfo = new HashMap<>();

	browseMoreCustomList.clear();
	browseMoreCustomInfo.put("img", "SF_101_UP_5?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Presentation Folders");
	browseMoreCustomInfo.put("link", "category?categoryId=letter");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "PRB_8801_Up_Inside?fmt=png-alpha&amp;wid=180&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Binders");
	browseMoreCustomInfo.put("link", "product/~product_id=PRB-8801");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "EF-146_COL_2_UP?fmt=png-alpha&amp;wid=180&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Certificate Holders & Folios");
	browseMoreCustomInfo.put("link", "product/~product_id=CHEL-185");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "hp-cardHolders?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Small Folders");
	browseMoreCustomInfo.put("link", "product/~product_id=HF-6801");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "LAW_SPOT_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Legal Folders");
	browseMoreCustomInfo.put("link", "product/~product_id=LF-118");
	browseMoreCustomList.add(browseMoreCustomInfo);

	browseMoreBlankList.clear();
	browseMoreBlankInfo.put("img", "SF-101_DARK_BLUE_100LB_LINEN_PERS?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreBlankInfo.put("text", "Presentation Folders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=SF-101");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "PB-2RREBLUE?fmt=png-alpha&amp;wid=180&amp;hei=185");
	browseMoreBlankInfo.put("text", "Binders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=PB-2RREBLUE");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "EF-146_COL_2_UP?fmt=png-alpha&amp;wid=150&amp;hei=185");
	browseMoreBlankInfo.put("text", "Folios");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=CHEL-185-DDBLK100-F");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "MF-144-DDP100?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreBlankInfo.put("text", "Small Folders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=MF-144");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "LF-118-DDBLU100?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreBlankInfo.put("text", "Legal Folders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=LF-118");
	browseMoreBlankList.add(browseMoreBlankInfo);

} else if (industryType.equals("customCharityFolders")) {
	industryInfo.put("h1", "Custom Charity Folders");
	industryInfo.put("bannerTextDesktop", "Custom charity folders & custom folders for organizations can help create awareness for your charity or fundraising efforts. Grab the attention of sponsors and volunteers with eye-catching visuals, including a variety of styles, textures & color options. Why not use every opportunity to attract new supporters!");
	industryInfo.put("customerExamplesHeader", "Custom Charity Folder Examples");
	industryInfo.put("customerExamplesText", "Customize your organization's folders with a variety of printing methods, including Full Color Printing, Spot Color, Foil Stamping, Embossing and more. See how customers in your industry are customizing their folders to stay on brand.");
	industryInfo.put("customProductHeader", "Browse More Custom Charity Folders");
	industryInfo.put("browseMoreCustomCopy", "Custom Products for your organization will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("blankProductHeader", "Browse More Blank Charity Folders");
	industryInfo.put("browseBlankCopy", "Shop from our numerous blank stock products for your organization.");
	industryInfo.put("customerReview", "Great quality products and service! I wasn't sure what type of folder I should order for my Charity, but the Sales Rep talked me through the options that would make our organization stand out! I got free delivery and the folders look amazing!");
	industryInfo.put("customerReviewName", "Charlotte Myers");
	industryInfo.put("customerReviewCompany", "Healing Hearts Foundation");

	productInfo.put("id", "SF_101_Up_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "SF_101_Up_9");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "3501-C-STANDING");
	productInfo.put("link", "product/~product_id=EFL-3501");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "CHAR_EMB_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "3DF_152_Up_3");
	productInfo.put("link", "product/~product_id=08-96");
	productList.add(productInfo);
	productInfo = new HashMap<>();

} else if (industryType.equals("customChurchFolders")) {
	industryInfo.put("h1", "Custom Church Folders");
	industryInfo.put("bannerTextDesktop", "Custom church folders & custom religious folders are a great way to provide information to church guests and community members. They can easily be customized for simple or inspirational designs to suit your needs. You can create custom church folders in a variety of styles, uniquely decorated with spot color, full-color, foil stamping and embossing.");
	industryInfo.put("customerExamplesHeader", "Custom Church Folder Examples");
	industryInfo.put("customerExamplesText", "Customize your church folders with a variety of printing methods, including Full Color Printing, Spot Color, Foil Stamping, Embossing and more. See how customers in your industry are customizing their folders to stay on brand.");
	industryInfo.put("customProductHeader", "Browse More Custom Church Folders");
	industryInfo.put("browseMoreCustomCopy", "Custom Products for your church will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("blankProductHeader", "Browse More Blank Church Folders");
	industryInfo.put("browseBlankCopy", "Shop from our numerous blank stock products for your church.");
	industryInfo.put("customerReview", "Our new church welcome folders came out great. I couldn't be happier with my order. Outstanding quality and service.");
	industryInfo.put("customerReviewName", "Margaret Smith");
	industryInfo.put("customerReviewCompany", "Lewiston Lutheran Church");

	productInfo.put("id", "REL_FOIL_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "3DF_139_Up_1");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "REL_SPOT_1");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "REL_EMB_1_D");
	productInfo.put("link", "product/~product_id=SF-101?printingType=Blind%20Embossing");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "CKH-2703-A-STANDING");
	productInfo.put("link", "product/~product_id=CKH-2703");
	productList.add(productInfo);
	productInfo = new HashMap<>();

} else if (industryType.equals("customInsuranceFolders")) {
	industryInfo.put("h1", "Insurance File Folders");
	industryInfo.put("bannerTextDesktop", "High quality custom folders for insurance brokers. Make your presentations stand out with stunning custom pocket folders, available in a variety of textures and styles. Put your company's best image forward by presenting financial data and proposals with a professional touch.");
	industryInfo.put("customerExamplesHeader", "Custom Insurance Folder Examples");
	industryInfo.put("customerExamplesText", "Customize your insurance folders with a variety of printing methods, including Full Color Printing, Spot Color, Foil Stamping, Embossing and more. See how customers in your industry are customizing their folders to stay on brand.");
	industryInfo.put("customProductHeader", "Browse More Custom Insurance Folders");
	industryInfo.put("browseMoreCustomCopy", "Custom Products for your insurance brokerage will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("blankProductHeader", "Browse More Blank Insurance Folders");
	industryInfo.put("browseBlankCopy", "Shop from our numerous blank stock products for your insurance brokerage.");
	industryInfo.put("customerReview", "I ordered custom 9 x 12 Presentation Folders for our Insurance Company and could not be more pleased that I chose Folders.com. Great customer service, fast turnaround, amazing quality and they price matched a competitors price.");
	industryInfo.put("customerReviewName", "Andrew Postiglione");
	industryInfo.put("customerReviewCompany", "New York Small Group Plans");

	productInfo.put("id", "3DF_139_Up_3_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "3DLE-2813-B-STANDING");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "INSU_SPOT_1");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "INSU_EMB_1_D");
	productInfo.put("link", "product/~category_id=STANDARD_FOLDER/~product_id=912-501-C");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "RCSTW-191-A-STANDING");
	productInfo.put("link", "product/~product_id=SF-102");
	productList.add(productInfo);
	productInfo = new HashMap<>();

} else if (industryType.equals("customHospitalityFolders")) {
	industryInfo.put("h1", "Custom Hotel Guest Folders");
	industryInfo.put("bannerTextDesktop", "Greet and inform members and guests with service information carefully organized in custom hospitality folders, custom hotel folders or custom spa folders. Ideal for providing hotel guests with welcome packs and key cards. Add foil stamping and embossing to enhance your professional image with beautifully designed custom hospitality folders.");
	industryInfo.put("customerExamplesHeader", "Custom Hospitality Folder Examples");
	industryInfo.put("customerExamplesText", "Customize your hospitality folders with a variety of printing methods, including Full Color Printing, Spot Color, Foil Stamping, Embossing and more. See how customers in your industry are customizing their folders to stay on brand.");
	industryInfo.put("customProductHeader", "Browse More Custom Hospitality Folders");
	industryInfo.put("browseMoreCustomCopy", "Custom Hospitality Products will help you stay on brand and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
	industryInfo.put("blankProductHeader", "Browse More Blank Hospitality Folders");
	industryInfo.put("browseBlankCopy", "Shop from our numerous blank stock products for your hotel and spa.");
	industryInfo.put("customerReview", "When we opened our day spa it was important that we have professional looking small folders to hold our sales materials. Not only do they look amazing, but they also didn't break our budget.");
	industryInfo.put("customerReviewName", "Stephanie Brand");
	industryInfo.put("customerReviewCompany", "Bliss Day Spa");

	productInfo.put("id", "CKH_2709_FOIL_1_UP_D");
	productInfo.put("link", "product/~product_id=CKH-2709");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "CKH_2709_Up_2");
	productInfo.put("link", "product/~product_id=CKH-2709");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "CKH-2704-C-STANDING");
	productInfo.put("link", "product/~product_id=CKH-2704");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "CKH-2705-C-STANDING_D");
	productInfo.put("link", "product/~product_id=SCKH-2705");
	productList.add(productInfo);
	productInfo = new HashMap<>();
	productInfo.put("id", "WP_0880_Up_1");
	productInfo.put("link", "product/~product_id=WP-0880");
	productList.add(productInfo);
	productInfo = new HashMap<>();

	browseMoreCustomList.clear();
	browseMoreCustomInfo.put("img", "CKH-2704-B-STANDING?fmt=png-alpha&amp;wid=160&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Key Card Holders");
	browseMoreCustomInfo.put("link", "category?categoryId=letter");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "PRB_8801_Up_Inside?fmt=png-alpha&amp;wid=180&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Binders");
	browseMoreCustomInfo.put("link", "product/~product_id=PRB-8801");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "SF_101_UP_5?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Presentation Folders");
	browseMoreCustomInfo.put("link", "product/~product_id=CHEL-185");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "hp-cardHolders?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Small Folders");
	browseMoreCustomInfo.put("link", "product/~product_id=HF-6801");
	browseMoreCustomList.add(browseMoreCustomInfo);
	browseMoreCustomInfo = new HashMap<>();
	browseMoreCustomInfo.put("img", "LAW_SPOT_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreCustomInfo.put("text", "Custom Legal Size Folders");
	browseMoreCustomInfo.put("link", "product/~product_id=LF-118");
	browseMoreCustomList.add(browseMoreCustomInfo);

	browseMoreBlankList.clear();
	browseMoreBlankInfo.put("img", "KHF-NLI?fmt=png-alpha&amp;wid=160&amp;hei=185");
	browseMoreBlankInfo.put("text", "Key Card Holders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=SF-101");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "PB-2RREBLUE?fmt=png-alpha&amp;wid=160&amp;hei=185");
	browseMoreBlankInfo.put("text", "Binders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=PB-2RREBLUE");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "SF-101_DARK_BLUE_100LB_LINEN_PERS?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreBlankInfo.put("text", "Presentation Folders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=CHEL-185-DDBLK100-F");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "MF-144-DDP100?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreBlankInfo.put("text", "Small Folders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=MF-144");
	browseMoreBlankList.add(browseMoreBlankInfo);
	browseMoreBlankInfo = new HashMap<>();
	browseMoreBlankInfo.put("img", "LF-118-DDBLU100?fmt=png-alpha&amp;wid=111&amp;hei=185");
	browseMoreBlankInfo.put("text", "Legal Size Folders");
	browseMoreBlankInfo.put("link", "blankProduct/~product_id=LF-118");
	browseMoreBlankList.add(browseMoreBlankInfo);

}

industryInfo.put("productList", productList);


context.industryInfo = industryInfo; 
context.browseMoreCustomList = browseMoreCustomList;
context.browseMoreBlankList = browseMoreBlankList;