import com.envelopes.util.*;

Map<String, Object> industryInfo = new HashMap<>();
Map<String, Object> productInfo = new HashMap<>();
List productList = new ArrayList<>();
Map<String, Object> browseMoreCustomInfo = new HashMap<>();
List browseMoreCustomList = new ArrayList<>();
Map<String, Object> browseMoreBlankInfo = new HashMap<>();
List browseMoreBlankList = new ArrayList<>();
Map<String, Object> params = EnvUtil.getParameterMap(request);
String productType = (String) params.get("id");

industryInfo.put("imageName", productType);

browseMoreCustomInfo.put("img", "SF_101_UP_5?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreCustomInfo.put("text", "Custom Presentation Folders");
browseMoreCustomInfo.put("link", "category?categoryId=letter");
browseMoreCustomList.add(browseMoreCustomInfo);
browseMoreCustomInfo = new HashMap<>();
browseMoreCustomInfo.put("img", "PRB_8801_Up_Inside?fmt=png-alpha&amp;wid=180&amp;hei=185");
browseMoreCustomInfo.put("text", "Custom Binders");
browseMoreCustomInfo.put("link", "product/~product_id=PRB-8801");
browseMoreCustomList.add(browseMoreCustomInfo);
browseMoreCustomInfo = new HashMap<>();
browseMoreCustomInfo.put("img", "CHEPF_185_Up_1_WDoc?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreCustomInfo.put("text", "Custom Certificate Holders & Report Covers");
browseMoreCustomInfo.put("link", "product/~product_id=CHEL-185");
browseMoreCustomList.add(browseMoreCustomInfo);
browseMoreCustomInfo = new HashMap<>();
browseMoreCustomInfo.put("img", "hp-cardHolders?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreCustomInfo.put("text", "Custom Small Folders");
browseMoreCustomInfo.put("link", "product/~product_id=HF-6801");
browseMoreCustomList.add(browseMoreCustomInfo);
browseMoreCustomInfo = new HashMap<>();
browseMoreCustomInfo.put("img", "LAW_SPOT_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreCustomInfo.put("text", "Custom Legal Folders");
browseMoreCustomInfo.put("link", "product/~product_id=LF-118");
browseMoreCustomList.add(browseMoreCustomInfo);

browseMoreBlankInfo.put("img", "SF-101_DARK_BLUE_100LB_LINEN_PERS?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreBlankInfo.put("text", "Presentation Folders");
browseMoreBlankInfo.put("link", "blankProduct/~product_id=SF-101");
browseMoreBlankList.add(browseMoreBlankInfo)
browseMoreBlankInfo = new HashMap<>();
browseMoreBlankInfo.put("img", "PB-2RREBLUE?fmt=png-alpha&amp;wid=180&amp;hei=185");
browseMoreBlankInfo.put("text", "Binders");
browseMoreBlankInfo.put("link", "blankProduct/~product_id=PB-2RREBLUE");
browseMoreBlankList.add(browseMoreBlankInfo);
browseMoreBlankInfo = new HashMap<>();
browseMoreBlankInfo.put("img", "CHEL-185-DDBLU100-F?fmt=png-alpha&amp;wid=130&amp;hei=185");
browseMoreBlankInfo.put("text", "Certificate Holders");
browseMoreBlankInfo.put("link", "blankProduct/~product_id=CHEL-185-DDBLK100-F");
browseMoreBlankList.add(browseMoreBlankInfo);
browseMoreBlankInfo = new HashMap<>();
browseMoreBlankInfo.put("img", "MF-144-DDP100-SMALL?fmt=png-alpha&amp;wid=180&amp;hei=185");
browseMoreBlankInfo.put("text", "Small Folders");
browseMoreBlankInfo.put("link", "blankProduct/~product_id=MF-144");
browseMoreBlankList.add(browseMoreBlankInfo);
browseMoreBlankInfo = new HashMap<>();
browseMoreBlankInfo.put("img", "LF-118-DDBLU100?fmt=png-alpha&amp;wid=111&amp;hei=185");
browseMoreBlankInfo.put("text", "Legal Size Folders");
browseMoreBlankInfo.put("link", "blankProduct/~product_id=LF-118");
browseMoreBlankList.add(browseMoreBlankInfo);

if (productType.equals("customLegalSizeFolders")) {
    industryInfo.put("h1", "Custom Legal Size Folders");
    industryInfo.put("bannerTextDesktop", "Legal Size Folders for law firms, mortgage companies & title companies. Perfect for holding and presenting large documents. Available as blank products or with custom printing.");
    industryInfo.put("customerExamplesHeader", "Custom Legal Size Folder Examples");
    industryInfo.put("customerExamplesText", "Customize your Legal Size Folders with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their Legal Size Folders to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Legal Size Folders with other custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank Legal Size Folders and other products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "So happy with our new Legal Folders from Folders.com! The gold foil stamping on the blue linen makes our brand logo really pop! The folders look so elegant and professional. Love!");
    industryInfo.put("customerReviewName", "Cameron Gutwein");
    industryInfo.put("customerReviewCompany", "D&G Law Office");

    productInfo.put("id", "LF_118_FOIL_UP_1_D");
    productInfo.put("link", "LF-118");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "LF-1401-COL_1_UP");
    productInfo.put("link", "LF-118");
    productInfo.put("printType", "Full Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "LF-1401_SCOL_1_UP");
    productInfo.put("link", "LF-118");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "LEGAL_EMB_1_D");
    productInfo.put("link", "LF-118");
    productInfo.put("printType", "Embossed");
    productList.add(productInfo);
    productInfo = new HashMap<>();

    browseMoreCustomList.clear();
    browseMoreCustomInfo.put("img", "SF_101_UP_5?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Presentation Folders");
    browseMoreCustomInfo.put("link", "category?categoryId=letter");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "PRB_8801_Up_Inside?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Binders");
    browseMoreCustomInfo.put("link", "product/~product_id=PRB-8801");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "CHEPF_185_Up_1_WDoc?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Certificate Holders & Report Covers");
    browseMoreCustomInfo.put("link", "product/~product_id=CHEL-185");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "CKH-2705_COL_UP_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Card Holders");
    browseMoreCustomInfo.put("link", "product/~product_id=HF-6801");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "LAW_SPOT_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Legal Folders");
    browseMoreCustomInfo.put("link", "product/~product_id=LF-118");
    browseMoreCustomList.add(browseMoreCustomInfo);

} else if (productType.equals("customCardHolders")) {
    industryInfo.put("h1", "Custom Card Holders");
    industryInfo.put("bannerTextDesktop", "Card Holders are ideal for gift cards, key cards, ID cards and more. Whether you prefer custom designed or blank, we have card holders to suit your needs.");
    industryInfo.put("customerExamplesHeader", "Custom Card Holder Examples");
    industryInfo.put("customerExamplesText", "Customize your Card Holders with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their Card Holders to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Card Holders with other custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, legal size folders, certificate holders, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank Card Holders and other products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "We received our new custom card holders today! I never thought I would be so excited about card holders, but they look amazing! The team at Folders.com was super helpful from the time i requested a quote to final proof approval. We will definitely be ordering from them again. Great service!");
    industryInfo.put("customerReviewName", "Marisa Lyons");
    industryInfo.put("customerReviewCompany", "Outlook Point Spa");

    productInfo.put("id", "CKH-2711_FOIL_1_UP_D");
    productInfo.put("link", "CKH-2709");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "CKH-2705_COL_UP_1");
    productInfo.put("link", "CKH-2709");
    productInfo.put("printType", "Full Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "CKH-2703_SCOL_2_UP");
    productInfo.put("link", "CKH-2709");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "CKH-2705-C-STANDING_D");
    productInfo.put("link", "CKH-2709");
    productInfo.put("printType", "Embossed");
    productList.add(productInfo);
    productInfo = new HashMap<>();


    browseMoreBlankList.clear();
    browseMoreBlankInfo.put("img", "SF-101_DARK_BLUE_100LB_LINEN_PERS?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Presentation Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=SF-101");
    browseMoreBlankList.add(browseMoreBlankInfo)
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "KHF-NLI?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreBlankInfo.put("text", "Card Holders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=PB-2RREBLUE");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "CHEL-185-DDBLU100-F?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreBlankInfo.put("text", "Diploma Covers");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=CHEL-185-DDBLK100-F");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "MF-144-DDP100?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Small Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=MF-144");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "LF-118-DDBLU100?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Legal Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=LF-118");
    browseMoreBlankList.add(browseMoreBlankInfo);

} else if (productType.equals("customPresentationFolders")) {
    industryInfo.put("h1", "Custom 9 x 12 Presentation Folders");
    industryInfo.put("bannerTextDesktop", "9 x 12 Presentation Folders are perfect for any industry need. With a plethora of pocket styles and decorative options to choose from, you can create a professional first impression and stay on brand.");
    industryInfo.put("customerExamplesHeader", "Custom 9 x 12 Presentation Folder Examples");
    industryInfo.put("customerExamplesText", "Customize your 9 x 12 Folders with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their presentation folders to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your 9x12 Presentation Folders with other custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, certificate holders, report covers, legal sized folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank 9x12 Folders and other products. Choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "5 stars all the way! My sales rep at Folders.com was super knowledgable about the products and went above and beyond to help me customize my presentation folders just the way I wanted.The full color printing is spot on!");
    industryInfo.put("customerReviewName", "Kylie Baptista");
    industryInfo.put("customerReviewCompany", "JQ Marketing Group");

    productInfo.put("id", "SF-0828_FOIL_1_UP_D");
    productInfo.put("link", "08-96-FOIL");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "SF_101_COL_1_UP");
    productInfo.put("link", "08-96");
    productInfo.put("printType", "Full Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "SF-0828_SCOL_1_UP");
    productInfo.put("link", "SF-101?printingType=Printed%20Folders");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "MED_EMB_1_D");
    productInfo.put("link", "SF-101?printingType=Blind%20Embossing");
    productInfo.put("printType", "Embossed");
    productList.add(productInfo);
    productInfo = new HashMap<>();

    browseMoreCustomList.clear();
    browseMoreCustomInfo.put("img", "CKH-2705_COL_UP_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Card Holders");
    browseMoreCustomInfo.put("link", "category?categoryId=letter");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "PRB_8801_Up_Inside?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Binders");
    browseMoreCustomInfo.put("link", "product/~product_id=PRB-8801");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "CHEPF_185_Up_1_WDoc?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Certificate Holders & Report Covers");
    browseMoreCustomInfo.put("link", "product/~product_id=CHEL-185");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "hp-cardHolders?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Small Folders");
    browseMoreCustomInfo.put("link", "product/~product_id=HF-6801");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "LAW_SPOT_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Legal Folders");
    browseMoreCustomInfo.put("link", "product/~product_id=LF-118");
    browseMoreCustomList.add(browseMoreCustomInfo);

} else if (productType.equals("customDiplomaCovers")) {
    industryInfo.put("h1", "Custom Diploma Covers");
    industryInfo.put("bannerTextDesktop", "Diploma Covers or Padded Diploma Covers are ideal for presenting awards and diplomas. Whether for a graduation or corporate event, make an impact by adding stunning decorative options or keep it classic with our blank styles.");
    industryInfo.put("customerExamplesHeader", "Custom Diploma Cover Examples");
    industryInfo.put("customerExamplesText", "Customize your Diploma Covers with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their diploma covers to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Diploma Covers with other custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, legal size folders, certificate holders, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank Diploma Covers and other products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "We orderd our new custom diploma covers from Folders.com and are so pleased with not only the product but the service as well! There were a variety of options and the sales rep helped us get samples to guide us in our decision making. The diploma covers look fantastic! You rock Folders.com team!");
    industryInfo.put("customerReviewName", "Theo James Zayn");
    industryInfo.put("customerReviewCompany", "East Meadow School of Music & Art");

    productInfo.put("id", "PDC-6X8_FOIL_2_UP_D");
    productInfo.put("link", "PDCL-8.5x11");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "PDCP-8-5X11_COL_1_UP");
    productInfo.put("link", "PDCL-8.5x11");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();

    browseMoreBlankList.clear();
    browseMoreBlankInfo.put("img", "SF-101_DARK_BLUE_100LB_LINEN_PERS?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Presentation Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=SF-101");
    browseMoreBlankList.add(browseMoreBlankInfo)
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "PB-2RREBLUE?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreBlankInfo.put("text", "Binders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=PB-2RREBLUE");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "CHEL-185-DDBLU100-F?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreBlankInfo.put("text", "Diploma Covers");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=CHEL-185-DDBLK100-F");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "MF-144-DDP100?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Small Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=MF-144");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "LF-118-DDBLU100?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Legal Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=LF-118");
    browseMoreBlankList.add(browseMoreBlankInfo);

} else if (productType.equals("customSmallFolders")) {
    industryInfo.put("h1", "Custom Small Folders");
    industryInfo.put("bannerTextDesktop", "Small Folders are ideal for presenting smaller inserts and booklets with a range of size options to suit various needs. Choose beautiful custom printing or keep it classic with our blank options.");
    industryInfo.put("customerExamplesHeader", "Custom Small Folder Examples");
    industryInfo.put("customerExamplesText", "Customize your Small Folders with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their small folders to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Small Folders with other custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, legal size folders, certificate holders, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank Small Folders and other products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "We ordered small welcome folders for our church's new members to receive. The pre-printed options Folders.com offered were exactly what our parish needed. Both attractive and affordable products!");
    industryInfo.put("customerReviewName", "Megan Cosgrove");
    industryInfo.put("customerReviewCompany", "St. Paul's Church of the Holy Spirit");

    productInfo.put("id", "CKH_2709_FOIL_1_UP_D");
    productInfo.put("link", "SF-101?printingType=Foil%20Stamped");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "HF_6801_Up");
    productInfo.put("link", "08-96");
    productInfo.put("printType", "Full Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "SMALLFOLDER_SPOT_1");
    productInfo.put("link", "SF-101?printingType=Printed%20Folders");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "SMALLFOLDER_EMB_1_D");
    productInfo.put("link", "CHEL-185");
    productInfo.put("printType", "Embossed");
    productList.add(productInfo);
    productInfo = new HashMap<>();

    browseMoreCustomList.clear();
    browseMoreCustomInfo.put("img", "SF_101_UP_5?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Presentation Folders");
    browseMoreCustomInfo.put("link", "category?categoryId=letter");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "PRB_8801_Up_Inside?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Binders");
    browseMoreCustomInfo.put("link", "product/~product_id=PRB-8801");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "CHEPF_185_Up_1_WDoc?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Certificate Holders & Report Covers");
    browseMoreCustomInfo.put("link", "product/~product_id=CHEL-185");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "CKH-2705_COL_UP_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Card Holders");
    browseMoreCustomInfo.put("link", "product/~product_id=HF-6801");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "LAW_SPOT_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Legal Folders");
    browseMoreCustomInfo.put("link", "product/~product_id=LF-118");
    browseMoreCustomList.add(browseMoreCustomInfo);

} else if (productType.equals("customCertificateHolders")) {
    industryInfo.put("h1", "Custom Certificate Holders/Report Covers");
    industryInfo.put("bannerTextDesktop", "Certificate Holders and Report Covers are ideal for showcasing presentations, documents and certificates, whether portrait or landscape orientation. Choose custom printing or keep it classic with our blank options.");
    industryInfo.put("customerExamplesHeader", "Custom Certificate Holder Examples");
    industryInfo.put("customerExamplesText", "Customize your Certificate Holders and Report Covers with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their certificate holders and report covers to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Certificate Holders and Report Covers with other custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, legal sized folders, card holders, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank Certificate Holders and Report Covers and other products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "Pleasantly suprised by the quality of products and service! We ordered custom report covers for the firm and were walked through the entire customization process. Will definitely be coming back to Folders.com to reorder!");
    industryInfo.put("customerReviewName", "Ken Sterling");
    industryInfo.put("customerReviewCompany", "Mahoney & Mahoney LLP");

    productInfo.put("id", "CHEPF_185_FOIL_1_UP_DOC_D");
    productInfo.put("link", "SF-101?printingType=Foil%20Stamped");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "RCW-0909_COL_1_UP");
    productInfo.put("link", "08-96");
    productInfo.put("printType", "Full Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "CHEL-186_SCOL_1_UP");
    productInfo.put("link", "SF-101?printingType=Printed%20Folders");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "UNI_EMB_1_D");
    productInfo.put("link", "SF-101?printingType=Blind%20Embossing");
    productInfo.put("printType", "Embossed");
    productList.add(productInfo);
    productInfo = new HashMap<>();

    browseMoreCustomList.clear();
    browseMoreCustomInfo.put("img", "SF_101_UP_5?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Presentation Folders");
    browseMoreCustomInfo.put("link", "category?categoryId=letter");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "PRB_8801_Up_Inside?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Binders");
    browseMoreCustomInfo.put("link", "product/~product_id=PRB-8801");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "CKH-2705_COL_UP_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Card Holders");
    browseMoreCustomInfo.put("link", "product/~product_id=CHEL-185");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "hp-cardHolders?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Small Folders");
    browseMoreCustomInfo.put("link", "product/~product_id=HF-6801");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "LAW_SPOT_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Legal Folders");
    browseMoreCustomInfo.put("link", "product/~product_id=LF-118");
    browseMoreCustomList.add(browseMoreCustomInfo);

} else if (productType.equals("blankFolders")) {
    industryInfo.put("h1", "Blank Folders");
    industryInfo.put("bannerTextDesktop", "Our range of blank folders are ideal for delivering all types of documents, presentations, sales collateral, resumes and more. These ready to ship folders are available in a variety of sizes with choice of pockets to match each unique requirement. Keep important documents covered, protected, and organized in these multi-purpose, high-quality plain folders.");
    industryInfo.put("customerExamplesHeader", "Custom Blank Folder Examples");
    industryInfo.put("customerExamplesText", "");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Blank Folders with our custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, legal size folders, certificate holders, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "Teaching a few different periods throughout the school day, I needed to have enough folders for my students that were sturdy and would keep their papers secure in the fasteners. The assorted pack of presentation folders with brads from Folders.com was the perfect solution.");
    industryInfo.put("customerReviewName", "John Holloway");
    industryInfo.put("customerReviewCompany", "5th Avenue Middle School");

    productInfo.put("id", "");
    productInfo.put("link", "SF-101?printingType=Foil%20Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "");
    productInfo.put("link", "08-96");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "");
    productInfo.put("link", "SF-101?printingType=Printed%20Folders");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "");
    productInfo.put("link", "SF-101?printingType=Blind%20Embossing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "");
    productInfo.put("link", "CM-1614");
    productList.add(productInfo);
    productInfo = new HashMap<>();

} else if (productType.equals("customBinders")) {
    industryInfo.put("h1", "Custom Binders");
    industryInfo.put("bannerTextDesktop", "Binders help to protect important documents and are ideal for organizing and displaying large amounts of content. Choose from a range of custom decorated and blank binders.");
    industryInfo.put("customerExamplesHeader", "Custom Binder Examples");
    industryInfo.put("customerExamplesText", "Customize your Binders with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their binders to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Binders with other custom products you need to stay organized and get you noticed. Choose between our various customization options for legal sized folders, card holders, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank Binders and other products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "Great quality products and service! I wasn't sure what type of folder I should order for my Charity, but the Sales Rep talked me through the options that would make our organization stand out! I got free delivery and the folders look amazing!");
    industryInfo.put("customerReviewName", "Charlotte Myers");
    industryInfo.put("customerReviewCompany", "Healing Hearts Foundation");

    productInfo.put("id", "BINDERS_FOIL_1_D");
    productInfo.put("link", "SF-101?printingType=Foil%20Stamped");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "PRBRE-8871_COL_1_UP");
    productInfo.put("link", "08-96");
    productInfo.put("printType", "Full Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "PRB-8801-ECO_SCOL_1_UP");
    productInfo.put("link", "EFL-3501");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "BINDERS_EMB_1_D");
    productInfo.put("link", "SF-101?printingType=Blind%20Embossing");
    productInfo.put("printType", "Embossed");
    productList.add(productInfo);
    productInfo = new HashMap<>();

    browseMoreCustomList.clear();
    browseMoreCustomInfo.put("img", "SF_101_UP_5?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Presentation Folders");
    browseMoreCustomInfo.put("link", "category?categoryId=letter");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "CKH-2705_COL_UP_1?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Card Holders");
    browseMoreCustomInfo.put("link", "product/~product_id=PRB-8801");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "CHEPF_185_Up_1_WDoc?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Certificate Holders & Report Covers");
    browseMoreCustomInfo.put("link", "product/~product_id=CHEL-185");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "hp-cardHolders?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Small Folders");
    browseMoreCustomInfo.put("link", "product/~product_id=HF-6801");
    browseMoreCustomList.add(browseMoreCustomInfo);
    browseMoreCustomInfo = new HashMap<>();
    browseMoreCustomInfo.put("img", "LAW_SPOT_1?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreCustomInfo.put("text", "Custom Legal Folders");
    browseMoreCustomInfo.put("link", "product/~product_id=LF-118");
    browseMoreCustomList.add(browseMoreCustomInfo);

} else if (productType.equals("customCapacityFolders")) {
    industryInfo.put("h1", "Custom Capacity Folders");
    industryInfo.put("bannerTextDesktop", "Capacity Folders are ideal for holding bulky documents, brochures or booklets, effortlessly. Choose from a range of custom printing options or opt for ready to ship blank expandable folders.");
    industryInfo.put("customerExamplesHeader", "Custom Capacity Folder Examples");
    industryInfo.put("customerExamplesText", "Customize your Capacity Folders with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their Capacity Folders to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Capacity Folders with other custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, legal size folders, certificate holders, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank Capacity Folders and other products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "My insurance company needed folders that could hold a bit more literature than a standard folder can. Folders.com offers folders with capacity pockets that are sturdy enough for brochures and pamphlets for our clients, and we were able to personalize with foil stamping of our logo!");
    industryInfo.put("customerReviewName", "Pete Barresi");
    industryInfo.put("customerReviewCompany", "Cooper Lynch Agency");

    productInfo.put("id", "3DF-0802_FOIL_1_UP_D");
    productInfo.put("link", "SF-101?printingType=Foil%20Stamped");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "3DE-2872_COL_1_UP");
    productInfo.put("link", "08-96");
    productInfo.put("printType", "Full Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "3DE-2872_SCOL_1_UP");
    productInfo.put("link", "SF-101?printingType=Printed%20Folders");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "ACC_EMB_1_D");
    productInfo.put("link", "SF-101?printingType=Blind%20Embossing");
    productInfo.put("printType", "Embossed");
    productList.add(productInfo);
    productInfo = new HashMap<>();

    browseMoreBlankList.clear();
    browseMoreBlankInfo.put("img", "SF-101_DARK_BLUE_100LB_LINEN_PERS?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Presentation Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=SF-101");
    browseMoreBlankList.add(browseMoreBlankInfo)
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "PB-2RREBLUE?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreBlankInfo.put("text", "Binders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=PB-2RREBLUE");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "CHEL-185-DDBLU100-F?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Certificate Holders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=CHEL-185-DDBLK100-F");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "MF-144-DDP100?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Small Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=MF-144");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "CON-912F-DBLI?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Capacity Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=LF-118");
    browseMoreBlankList.add(browseMoreBlankInfo);

} else if (productType.equals("customFolios")) {
    industryInfo.put("h1", "Custom Folios/Totes");
    industryInfo.put("bannerTextDesktop", "Folios and Totes are ideal for displaying work samples, documents and visuals. Make your display distinctly unique by utilizing custom design and color features or choose ready to ship blank expandable folders.");
    industryInfo.put("customerExamplesHeader", "Custom Folios/Totes Examples");
    industryInfo.put("customerExamplesText", "Customize your Folios with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their folios and totes to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Folios with other custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, legal size folders, certificate holders, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank Folios and other products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "Our firm needed custom folios to organize and provide documents to our clients and we could not be happier with the product. Great quality and the Folders.com sales reps really helped us through the process.");
    industryInfo.put("customerReviewName", "Andrew Postiglione");
    industryInfo.put("customerReviewCompany", "New York Small Group Plans");

    productInfo.put("id", "07564_FOIL_UP_1_D");
    productInfo.put("link", "EF-146");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "1611_COL_1_UP");
    productInfo.put("link", "EF-146");
    productInfo.put("printType", "Full Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "1601_SCOL_1_UP");
    productInfo.put("link", "EF-146");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "EF-155_EMB_1_UP_D");
    productInfo.put("link", "EF-146");
    productInfo.put("printType", "Embossed");
    productList.add(productInfo);
    productInfo = new HashMap<>();

    browseMoreBlankList.clear();
    browseMoreBlankInfo.put("img", "SF-101_DARK_BLUE_100LB_LINEN_PERS?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Presentation Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=SF-101");
    browseMoreBlankList.add(browseMoreBlankInfo)
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "PB-2RREBLUE?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreBlankInfo.put("text", "Binders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=PB-2RREBLUE");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "CHEL-185-DDBLU100-F?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Certificate Holders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=CHEL-185-DDBLK100-F");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "MF-144-DDP100?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Small Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=MF-144");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "F-1602?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreBlankInfo.put("text", "Folios / Totes");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=LF-118");
    browseMoreBlankList.add(browseMoreBlankInfo);

} else if (productType.equals("customVerticalPocketFolders")) {
    industryInfo.put("h1", "Custom Vertical Pocket Folders");
    industryInfo.put("bannerTextDesktop", "Vertical Pocket Folders feature a vertical sleeve for holding magazines and booklets and are die-cut for an ultra-smart look. Create a lasting impression with powerful custom designs in a range of premium print options.");
    industryInfo.put("customerExamplesHeader", "Custom Vertical Pocket Folder Examples");
    industryInfo.put("customerExamplesText", "Customize your Vertical Pocket Folders with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their Vertical Pocket Folders to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Vertical Pocket Folders with other custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, legal size folders, certificate holders, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank Vertical Pocket Folders and other products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "Folders.com helped us find the perfect folders to hold our new sales literature. They look great and really brought our in person marketing tools to the next level. Thanks Andy!");
    industryInfo.put("customerReviewName", "Mike Maloney");
    industryInfo.put("customerReviewCompany", "MM&GS Consultants");

    productInfo.put("id", "V1-0851_FOIL_1_UP_D");
    productInfo.put("link", "VS-122");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "VS-167_COL_1_UP");
    productInfo.put("link", "VS-122");
    productInfo.put("printType", "Full Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "V1-0852_SCOL_1_UP");
    productInfo.put("link", "VS-122");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "VERTICAL_EMB_1_D");
    productInfo.put("link", "VS-122");
    productInfo.put("printType", "Embossed");
    productList.add(productInfo);
    productInfo = new HashMap<>();

} else if (productType.equals("customReinforcedFolders")) {
    industryInfo.put("h1", "Custom Reinforced Folders");
    industryInfo.put("bannerTextDesktop", "Reinforced Folders offer superb durability for the transportation and handling of bulky documents. Take advantage of a range of personalized print options to emphasize your brand image or opt for our blank reinforced folders.");
    industryInfo.put("customerExamplesHeader", "Custom Reinforced Folder Examples");
    industryInfo.put("customerExamplesText", "Customize your Reinforced Folders with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their Reinforced Folders to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Reinforced Folders with other custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, legal size folders, certificate holders, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank Reinforced Folders and other products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "When we needed a really tough, durable folder to hold our heavy sales packets and last in the field, Lee found the perfect product to not only do the job but look great. Thanks!");
    industryInfo.put("customerReviewName", "Kevin Conway");
    industryInfo.put("customerReviewCompany", "Conway Restaurant Supply");

    productInfo.put("id", "REINFORCED_FOIL_1_D");
    productInfo.put("link", "RE-2971");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "RE_2971_COL_1_UP");
    productInfo.put("link", "RE-2971");
    productInfo.put("printType", "Full Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "REINFORCED_SCOL_1");
    productInfo.put("link", "RE-2971");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "REINFORCED_EMB_1_D");
    productInfo.put("link", "RE-2971");
    productInfo.put("printType", "Embossed");
    productList.add(productInfo);
    productInfo = new HashMap<>();

} else if (productType.equals("customPhotoHolders")) {
    industryInfo.put("h1", "Custom Photo Holders");
    industryInfo.put("bannerTextDesktop", "Photo Holders are ideal for displaying and presenting photos in landscape or portrait format. Choose from 8 x 10 or 5 x 7 photo holders and customize with decorative options for that extra-special appeal.");
    industryInfo.put("customerExamplesHeader", "Custom Photo Holder Examples");
    industryInfo.put("customerExamplesText", "Customize your Photo Holders with our various printing methods, including Full Color Printing, Foil Stamping, Embossing and more. See how other customers personalized their Photo Holders to stay on brand.");
    industryInfo.put("customProductHeader", "Browse More Custom Products");
    industryInfo.put("browseMoreCustomCopy", "Pair your Photo Holders with other custom products you need to stay organized and get you noticed. Choose between our various customization options for binders, legal size folders, certificate holders, presentation folders and more!");
    industryInfo.put("blankProductHeader", "Browse More Blank Products");
    industryInfo.put("browseBlankCopy", "Browse our large selection of blank Photo Holders and other products, choose the styles and features that best fit your needs.");
    industryInfo.put("customerReview", "The custom photo holders I purchased from Folders.com are great. My clients really love the available colors and they're great for my personal company branding.");
    industryInfo.put("customerReviewName", "Rebekkah Rhoades ");
    industryInfo.put("customerReviewCompany", "High Rhoade Photo");

    productInfo.put("id", "PHOTO_FOIL_1_D");
    productInfo.put("link", "PHLS-0308");
    productInfo.put("printType", "Foil Stamped");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "PHOTO_COL_1");
    productInfo.put("link", "PHLS-0308");
    productInfo.put("printType", "Full Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "PHOTO_SCOL_1");
    productInfo.put("link", "PHLS-0308");
    productInfo.put("printType", "Spot Color Printing");
    productList.add(productInfo);
    productInfo = new HashMap<>();
    productInfo.put("id", "PHOTO_EMB_1_D");
    productInfo.put("link", "PHLS-0308");
    productInfo.put("printType", "Embossed");
    productList.add(productInfo);
    productInfo = new HashMap<>();

    browseMoreBlankList.clear();
    browseMoreBlankInfo.put("img", "SF-101_DARK_BLUE_100LB_LINEN_PERS?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Presentation Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=SF-101");
    browseMoreBlankList.add(browseMoreBlankInfo)
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "PB-2RREBLUE?fmt=png-alpha&amp;wid=180&amp;hei=185");
    browseMoreBlankInfo.put("text", "Binders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=PB-2RREBLUE");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "CHEL-185-DDBLU100-F?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Certificate Holders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=CHEL-185-DDBLK100-F");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "MF-144-DDP100?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Small Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=MF-144");
    browseMoreBlankList.add(browseMoreBlankInfo);
    browseMoreBlankInfo = new HashMap<>();
    browseMoreBlankInfo.put("img", "LF-118-DDBLU100?fmt=png-alpha&amp;wid=111&amp;hei=185");
    browseMoreBlankInfo.put("text", "Legal Folders");
    browseMoreBlankInfo.put("link", "blankProduct/~product_id=LF-118");
    browseMoreBlankList.add(browseMoreBlankInfo);

}

industryInfo.put("productList", productList);


context.industryInfo = industryInfo;
context.browseMoreCustomList = browseMoreCustomList;
context.browseMoreBlankList = browseMoreBlankList;