<div class="foldersContainer">
	<div class="foldersContainerContent">
		<div class="foldersContainerHeader">
			<h1 class="ftc-blue">Assemble Design Elements in a Page Layout Program</h1>
		</div>
		<div class="foldersContainerBody">
			<p>This is the best way to assemble the elements of your design. If at all possible we strongly recommend using a Layout program. The most widely supported layout programs are:&nbsp;<a href="<@ofbizUrl>infoArtworkIndesign</@ofbizUrl>">Adobe&nbsp;InDesign</a>&nbsp;and&nbsp;Adobe Illustrator.&nbsp;</p>
			<p>Layout programs exist to enable the designer to quickly and easily change the entire structure of a design or manipulate positioning of images and text in a document without disturbing other portions of the design.&nbsp;&nbsp;Failure to use a recommended layout program may result in additional charges.&nbsp; Note: Adobe Photoshop is NOT a layout program.</p>
			<p class="marginTop10"><strong class="ftc-blue">Checklist:<a href="<@ofbizUrl>/infoArtworkChecklist</@ofbizUrl>">&nbsp;InDesign&nbsp;and&nbsp;QuarkXPress</a></strong></p>
			<p class="marginTop10"><strong class="ftc-blue">Digital Templates</strong>: Before you begin, contact us for a digital template of the product style you have purchased, or download it from the website product page. Use our template in your layout program to properly position your design elements. Some areas of your design will be positioned "upside down" or rotated so they print correctly (see image below).&nbsp;&nbsp;Place or import the template file into your page layout program, and place it on a separate layer.</p>
			<p class="marginTop10"><strong class="ftc-blue">Fonts:</strong>&nbsp;DO NOT USE the font styles available in the&nbsp;fonts&nbsp;palette (i.e. bold or italic). You must have an actual bold or italic font file loaded to choose from in your font list in order for the font to print correctly. It will look fine on screen, probably print okay to a desktop inkjet or laser printer, but will not print correctly to a high-resolution output device. We will not be held responsible for fonts not imaging as you expected if you use the font styles palette.</p>
			<p>Check your document and verify you included all fonts used in your file. Review all text areas for extraneous blank spaces and extra "returns". If, while designing, you experimented with different fonts there may be fonts still attached to the text that are "hiding" blank spaces or extra returns between lines of text or at the ends of paragraphs or single lines of text. Verify there are no unused fonts remaining in your artwork by checking the list of fonts used in your documents file information. We will need ALL font files used in your document (even if the font only shows up in a blank space) before we can further process your document for printing. &nbsp;All fonts should be placed in a Zip or Stuffit file before being emailed or uploaded to avoid the possibility of being corrupted.</p>
			<p>NOTE: To eliminate the need to send your font files you may convert your text to "curves" or "outlines". Keep in mind though, once text is converted it cannot be edited (i.e. phone numbers, spelling mistakes, e-mail addresses, grammatical errors, etc. can't be changed). For the greatest flexibility we DO NOT recommend converting text to outlines or curves.</p>
			<p class="marginTop10"><strong class="ftc-blue">Bleeds &amp; File Sizes:&nbsp;</strong>Bleed is an extra amount of image or other elements that go beyond the finished trim size of your project (usually 1/8”). Once your job has been printed, we then cut it down to size, giving the appearance the image ‘bleeds’ off the edge of the final product rather than having a white or paper-colored border. Because the cutting is done in large stacks on machinery, there can be slight variances. Although the automated cutting machines are state of the art, some allowance must be made for shifting of the stack and/or the cutting blades.</p>
			<p class="marginTop10"><strong class="ftc-blue">Resolution:</strong>&nbsp;Be sure all photo-type images you place are at least 350 dpi and that you do not enlarge your images greater than 125% or reduce them to less than 30% in your layout file. If you find the need to enlarge, reduce or crop out your image by more than that, open the image file in Photoshop, resize/crop and resave.</p>
			<p class="marginTop10"><strong class="ftc-blue">Images:</strong>&nbsp;Be sure all placed color images are saved in CMYK color format. Place only correctly prepared tiff or&nbsp;epsfiles. Do not copy and paste images from a pasteboard or clip art program. This does not create a link to a high-resolution image. You must place or link images into your layout. Failure to do this will delay printing and shipping of your printed pieces while we contact you to upload/send us missing images. Don't forget to send all image files used in your design when sending your art files.</p>
		</div>
	</div>
</div>