//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.04 at 05:24:23 PM EDT 
//


package org.etsi.uri._01903.v1_3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.etsi.uri._01903.v1_3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NoticeRef_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "NoticeRef");
    private final static QName _CounterSignature_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CounterSignature");
    private final static QName _SigPolicyHash_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigPolicyHash");
    private final static QName _StateOrProvince_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "StateOrProvince");
    private final static QName _Identifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Identifier");
    private final static QName _OCSPIdentifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OCSPIdentifier");
    private final static QName _OtherValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OtherValues");
    private final static QName _SignedProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedProperties");
    private final static QName _Cert_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Cert");
    private final static QName _AllDataObjectsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AllDataObjectsTimeStamp");
    private final static QName _SPUserNotice_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SPUserNotice");
    private final static QName _OtherRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OtherRefs");
    private final static QName _AttributeCertificateRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeCertificateRefs");
    private final static QName _XMLTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "XMLTimeStamp");
    private final static QName _CommitmentTypeId_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CommitmentTypeId");
    private final static QName _EncapsulatedCRLValue_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "EncapsulatedCRLValue");
    private final static QName _CertDigest_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CertDigest");
    private final static QName _SignaturePolicyId_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignaturePolicyId");
    private final static QName _Int_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "int");
    private final static QName _SigningTime_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigningTime");
    private final static QName _PostalCode_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "PostalCode");
    private final static QName _SignerRole_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignerRole");
    private final static QName _IndividualDataObjectsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "IndividualDataObjectsTimeStamp");
    private final static QName _SignatureProductionPlace_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignatureProductionPlace");
    private final static QName _UnsignedSignatureProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedSignatureProperties");
    private final static QName _Include_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Include");
    private final static QName _CRLRef_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CRLRef");
    private final static QName _SigAndRefsTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigAndRefsTimeStamp");
    private final static QName _Description_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Description");
    private final static QName _CRLIdentifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CRLIdentifier");
    private final static QName _SignaturePolicyIdentifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignaturePolicyIdentifier");
    private final static QName _X509SerialNumber_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "X509SerialNumber");
    private final static QName _SigPolicyQualifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigPolicyQualifier");
    private final static QName _CommitmentTypeQualifiers_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CommitmentTypeQualifiers");
    private final static QName _OtherValue_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OtherValue");
    private final static QName _SignedSignatureProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedSignatureProperties");
    private final static QName _DataObjectFormat_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "DataObjectFormat");
    private final static QName _ClaimedRole_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ClaimedRole");
    private final static QName _Number_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Number");
    private final static QName _AttrAuthoritiesCertValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttrAuthoritiesCertValues");
    private final static QName _UnsignedDataObjectProperty_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedDataObjectProperty");
    private final static QName _ResponderID_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ResponderID");
    private final static QName _ByName_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ByName");
    private final static QName _UnsignedDataObjectProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedDataObjectProperties");
    private final static QName _Encoding_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Encoding");
    private final static QName _ExplicitText_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ExplicitText");
    private final static QName _OtherCertificate_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OtherCertificate");
    private final static QName _SigPolicyQualifiers_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigPolicyQualifiers");
    private final static QName _ArchiveTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ArchiveTimeStamp");
    private final static QName _EncapsulatedX509Certificate_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "EncapsulatedX509Certificate");
    private final static QName _CompleteRevocationRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CompleteRevocationRefs");
    private final static QName _AllSignedDataObjects_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AllSignedDataObjects");
    private final static QName _AttributeRevocationValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeRevocationValues");
    private final static QName _CertificateValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CertificateValues");
    private final static QName _RevocationValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "RevocationValues");
    private final static QName _CompleteCertificateRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CompleteCertificateRefs");
    private final static QName _SignatureTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignatureTimeStamp");
    private final static QName _AttributeRevocationRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "AttributeRevocationRefs");
    private final static QName _ObjectReference_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ObjectReference");
    private final static QName _SignaturePolicyImplied_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignaturePolicyImplied");
    private final static QName _ObjectIdentifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ObjectIdentifier");
    private final static QName _CertifiedRoles_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CertifiedRoles");
    private final static QName _IssuerSerial_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "IssuerSerial");
    private final static QName _X509IssuerName_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "X509IssuerName");
    private final static QName _CountryName_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CountryName");
    private final static QName _SigningCertificate_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigningCertificate");
    private final static QName _SigPolicyId_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SigPolicyId");
    private final static QName _OCSPRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OCSPRefs");
    private final static QName _CommitmentTypeQualifier_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CommitmentTypeQualifier");
    private final static QName _RefsOnlyTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "RefsOnlyTimeStamp");
    private final static QName _SignedDataObjectProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SignedDataObjectProperties");
    private final static QName _EncapsulatedTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "EncapsulatedTimeStamp");
    private final static QName _Issuer_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Issuer");
    private final static QName _NoticeNumbers_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "NoticeNumbers");
    private final static QName _Any_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Any");
    private final static QName _ByKey_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ByKey");
    private final static QName _ProducedAt_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ProducedAt");
    private final static QName _OCSPRef_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OCSPRef");
    private final static QName _EncapsulatedPKIData_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "EncapsulatedPKIData");
    private final static QName _City_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "City");
    private final static QName _UnsignedProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "UnsignedProperties");
    private final static QName _CRLValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CRLValues");
    private final static QName _EncapsulatedOCSPValue_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "EncapsulatedOCSPValue");
    private final static QName _OtherRef_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OtherRef");
    private final static QName _CertRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CertRefs");
    private final static QName _SPURI_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "SPURI");
    private final static QName _ReferenceInfo_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ReferenceInfo");
    private final static QName _OCSPValues_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OCSPValues");
    private final static QName _CommitmentTypeIndication_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CommitmentTypeIndication");
    private final static QName _QualifyingProperties_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "QualifyingProperties");
    private final static QName _CertifiedRole_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CertifiedRole");
    private final static QName _IssueTime_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "IssueTime");
    private final static QName _Organization_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "Organization");
    private final static QName _DocumentationReferences_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "DocumentationReferences");
    private final static QName _DigestAlgAndValue_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "DigestAlgAndValue");
    private final static QName _MimeType_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "MimeType");
    private final static QName _ClaimedRoles_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "ClaimedRoles");
    private final static QName _XAdESTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "XAdESTimeStamp");
    private final static QName _CRLRefs_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "CRLRefs");
    private final static QName _DocumentationReference_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "DocumentationReference");
    private final static QName _OtherTimeStamp_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "OtherTimeStamp");
    private final static QName _QualifyingPropertiesReference_QNAME = new QName("http://uri.etsi.org/01903/v1.3.2#", "QualifyingPropertiesReference");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.etsi.uri._01903.v1_3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocumentationReference }
     * 
     */
    public DocumentationReference createDocumentationReference() {
        return new DocumentationReference();
    }

    /**
     * Create an instance of {@link OtherTimeStamp }
     * 
     */
    public OtherTimeStamp createOtherTimeStamp() {
        return new OtherTimeStamp();
    }

    /**
     * Create an instance of {@link SigningCertificate }
     * 
     */
    public SigningCertificate createSigningCertificate() {
        return new SigningCertificate();
    }

    /**
     * Create an instance of {@link EncapsulatedCRLValue }
     * 
     */
    public EncapsulatedCRLValue createEncapsulatedCRLValue() {
        return new EncapsulatedCRLValue();
    }

    /**
     * Create an instance of {@link QualifyingPropertiesReference }
     * 
     */
    public QualifyingPropertiesReference createQualifyingPropertiesReference() {
        return new QualifyingPropertiesReference();
    }

    /**
     * Create an instance of {@link OtherValue }
     * 
     */
    public OtherValue createOtherValue() {
        return new OtherValue();
    }

    /**
     * Create an instance of {@link SigPolicyQualifier }
     * 
     */
    public SigPolicyQualifier createSigPolicyQualifier() {
        return new SigPolicyQualifier();
    }

    /**
     * Create an instance of {@link CRLRefs }
     * 
     */
    public CRLRefs createCRLRefs() {
        return new CRLRefs();
    }

    /**
     * Create an instance of {@link AttributeCertificateRefs }
     * 
     */
    public AttributeCertificateRefs createAttributeCertificateRefs() {
        return new AttributeCertificateRefs();
    }

    /**
     * Create an instance of {@link CommitmentTypeQualifiers }
     * 
     */
    public CommitmentTypeQualifiers createCommitmentTypeQualifiers() {
        return new CommitmentTypeQualifiers();
    }

    /**
     * Create an instance of {@link CommitmentTypeId }
     * 
     */
    public CommitmentTypeId createCommitmentTypeId() {
        return new CommitmentTypeId();
    }

    /**
     * Create an instance of {@link XMLTimeStamp }
     * 
     */
    public XMLTimeStamp createXMLTimeStamp() {
        return new XMLTimeStamp();
    }

    /**
     * Create an instance of {@link OtherRefs }
     * 
     */
    public OtherRefs createOtherRefs() {
        return new OtherRefs();
    }

    /**
     * Create an instance of {@link ClaimedRoles }
     * 
     */
    public ClaimedRoles createClaimedRoles() {
        return new ClaimedRoles();
    }

    /**
     * Create an instance of {@link CRLIdentifier }
     * 
     */
    public CRLIdentifier createCRLIdentifier() {
        return new CRLIdentifier();
    }

    /**
     * Create an instance of {@link SPUserNotice }
     * 
     */
    public SPUserNotice createSPUserNotice() {
        return new SPUserNotice();
    }

    /**
     * Create an instance of {@link SignaturePolicyIdentifier }
     * 
     */
    public SignaturePolicyIdentifier createSignaturePolicyIdentifier() {
        return new SignaturePolicyIdentifier();
    }

    /**
     * Create an instance of {@link X509SerialNumber }
     * 
     */
    public X509SerialNumber createX509SerialNumber() {
        return new X509SerialNumber();
    }

    /**
     * Create an instance of {@link XAdESTimeStamp }
     * 
     */
    public XAdESTimeStamp createXAdESTimeStamp() {
        return new XAdESTimeStamp();
    }

    /**
     * Create an instance of {@link IssuerSerial }
     * 
     */
    public IssuerSerial createIssuerSerial() {
        return new IssuerSerial();
    }

    /**
     * Create an instance of {@link DigestAlgAndValue }
     * 
     */
    public DigestAlgAndValue createDigestAlgAndValue() {
        return new DigestAlgAndValue();
    }

    /**
     * Create an instance of {@link DocumentationReferences }
     * 
     */
    public DocumentationReferences createDocumentationReferences() {
        return new DocumentationReferences();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link CountryName }
     * 
     */
    public CountryName createCountryName() {
        return new CountryName();
    }

    /**
     * Create an instance of {@link X509IssuerName }
     * 
     */
    public X509IssuerName createX509IssuerName() {
        return new X509IssuerName();
    }

    /**
     * Create an instance of {@link AllDataObjectsTimeStamp }
     * 
     */
    public AllDataObjectsTimeStamp createAllDataObjectsTimeStamp() {
        return new AllDataObjectsTimeStamp();
    }

    /**
     * Create an instance of {@link MimeType }
     * 
     */
    public MimeType createMimeType() {
        return new MimeType();
    }

    /**
     * Create an instance of {@link SignedProperties }
     * 
     */
    public SignedProperties createSignedProperties() {
        return new SignedProperties();
    }

    /**
     * Create an instance of {@link IssueTime }
     * 
     */
    public IssueTime createIssueTime() {
        return new IssueTime();
    }

    /**
     * Create an instance of {@link AttributeRevocationRefs }
     * 
     */
    public AttributeRevocationRefs createAttributeRevocationRefs() {
        return new AttributeRevocationRefs();
    }

    /**
     * Create an instance of {@link SigAndRefsTimeStamp }
     * 
     */
    public SigAndRefsTimeStamp createSigAndRefsTimeStamp() {
        return new SigAndRefsTimeStamp();
    }

    /**
     * Create an instance of {@link ObjectReference }
     * 
     */
    public ObjectReference createObjectReference() {
        return new ObjectReference();
    }

    /**
     * Create an instance of {@link SignaturePolicyImplied }
     * 
     */
    public SignaturePolicyImplied createSignaturePolicyImplied() {
        return new SignaturePolicyImplied();
    }

    /**
     * Create an instance of {@link Cert }
     * 
     */
    public Cert createCert() {
        return new Cert();
    }

    /**
     * Create an instance of {@link CertifiedRoles }
     * 
     */
    public CertifiedRoles createCertifiedRoles() {
        return new CertifiedRoles();
    }

    /**
     * Create an instance of {@link ObjectIdentifier }
     * 
     */
    public ObjectIdentifier createObjectIdentifier() {
        return new ObjectIdentifier();
    }

    /**
     * Create an instance of {@link RevocationValues }
     * 
     */
    public RevocationValues createRevocationValues() {
        return new RevocationValues();
    }

    /**
     * Create an instance of {@link OCSPValues }
     * 
     */
    public OCSPValues createOCSPValues() {
        return new OCSPValues();
    }

    /**
     * Create an instance of {@link CertifiedRole }
     * 
     */
    public CertifiedRole createCertifiedRole() {
        return new CertifiedRole();
    }

    /**
     * Create an instance of {@link CompleteCertificateRefs }
     * 
     */
    public CompleteCertificateRefs createCompleteCertificateRefs() {
        return new CompleteCertificateRefs();
    }

    /**
     * Create an instance of {@link QualifyingProperties }
     * 
     */
    public QualifyingProperties createQualifyingProperties() {
        return new QualifyingProperties();
    }

    /**
     * Create an instance of {@link CommitmentTypeIndication }
     * 
     */
    public CommitmentTypeIndication createCommitmentTypeIndication() {
        return new CommitmentTypeIndication();
    }

    /**
     * Create an instance of {@link CRLRef }
     * 
     */
    public CRLRef createCRLRef() {
        return new CRLRef();
    }

    /**
     * Create an instance of {@link SignatureTimeStamp }
     * 
     */
    public SignatureTimeStamp createSignatureTimeStamp() {
        return new SignatureTimeStamp();
    }

    /**
     * Create an instance of {@link CertRefs }
     * 
     */
    public CertRefs createCertRefs() {
        return new CertRefs();
    }

    /**
     * Create an instance of {@link AttributeRevocationValues }
     * 
     */
    public AttributeRevocationValues createAttributeRevocationValues() {
        return new AttributeRevocationValues();
    }

    /**
     * Create an instance of {@link SPURI }
     * 
     */
    public SPURI createSPURI() {
        return new SPURI();
    }

    /**
     * Create an instance of {@link OtherValues }
     * 
     */
    public OtherValues createOtherValues() {
        return new OtherValues();
    }

    /**
     * Create an instance of {@link ReferenceInfo }
     * 
     */
    public ReferenceInfo createReferenceInfo() {
        return new ReferenceInfo();
    }

    /**
     * Create an instance of {@link CertificateValues }
     * 
     */
    public CertificateValues createCertificateValues() {
        return new CertificateValues();
    }

    /**
     * Create an instance of {@link EncapsulatedOCSPValue }
     * 
     */
    public EncapsulatedOCSPValue createEncapsulatedOCSPValue() {
        return new EncapsulatedOCSPValue();
    }

    /**
     * Create an instance of {@link EncapsulatedX509Certificate }
     * 
     */
    public EncapsulatedX509Certificate createEncapsulatedX509Certificate() {
        return new EncapsulatedX509Certificate();
    }

    /**
     * Create an instance of {@link ArchiveTimeStamp }
     * 
     */
    public ArchiveTimeStamp createArchiveTimeStamp() {
        return new ArchiveTimeStamp();
    }

    /**
     * Create an instance of {@link AllSignedDataObjects }
     * 
     */
    public AllSignedDataObjects createAllSignedDataObjects() {
        return new AllSignedDataObjects();
    }

    /**
     * Create an instance of {@link UnsignedSignatureProperties }
     * 
     */
    public UnsignedSignatureProperties createUnsignedSignatureProperties() {
        return new UnsignedSignatureProperties();
    }

    /**
     * Create an instance of {@link CompleteRevocationRefs }
     * 
     */
    public CompleteRevocationRefs createCompleteRevocationRefs() {
        return new CompleteRevocationRefs();
    }

    /**
     * Create an instance of {@link Include }
     * 
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link OtherRef }
     * 
     */
    public OtherRef createOtherRef() {
        return new OtherRef();
    }

    /**
     * Create an instance of {@link ExplicitText }
     * 
     */
    public ExplicitText createExplicitText() {
        return new ExplicitText();
    }

    /**
     * Create an instance of {@link CRLValues }
     * 
     */
    public CRLValues createCRLValues() {
        return new CRLValues();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link OtherCertificate }
     * 
     */
    public OtherCertificate createOtherCertificate() {
        return new OtherCertificate();
    }

    /**
     * Create an instance of {@link SigPolicyQualifiers }
     * 
     */
    public SigPolicyQualifiers createSigPolicyQualifiers() {
        return new SigPolicyQualifiers();
    }

    /**
     * Create an instance of {@link OCSPIdentifier }
     * 
     */
    public OCSPIdentifier createOCSPIdentifier() {
        return new OCSPIdentifier();
    }

    /**
     * Create an instance of {@link IndividualDataObjectsTimeStamp }
     * 
     */
    public IndividualDataObjectsTimeStamp createIndividualDataObjectsTimeStamp() {
        return new IndividualDataObjectsTimeStamp();
    }

    /**
     * Create an instance of {@link StateOrProvince }
     * 
     */
    public StateOrProvince createStateOrProvince() {
        return new StateOrProvince();
    }

    /**
     * Create an instance of {@link Encoding }
     * 
     */
    public Encoding createEncoding() {
        return new Encoding();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link SignatureProductionPlace }
     * 
     */
    public SignatureProductionPlace createSignatureProductionPlace() {
        return new SignatureProductionPlace();
    }

    /**
     * Create an instance of {@link UnsignedProperties }
     * 
     */
    public UnsignedProperties createUnsignedProperties() {
        return new UnsignedProperties();
    }

    /**
     * Create an instance of {@link ProducedAt }
     * 
     */
    public ProducedAt createProducedAt() {
        return new ProducedAt();
    }

    /**
     * Create an instance of {@link ByKey }
     * 
     */
    public ByKey createByKey() {
        return new ByKey();
    }

    /**
     * Create an instance of {@link EncapsulatedPKIData }
     * 
     */
    public EncapsulatedPKIData createEncapsulatedPKIData() {
        return new EncapsulatedPKIData();
    }

    /**
     * Create an instance of {@link OCSPRef }
     * 
     */
    public OCSPRef createOCSPRef() {
        return new OCSPRef();
    }

    /**
     * Create an instance of {@link SignedDataObjectProperties }
     * 
     */
    public SignedDataObjectProperties createSignedDataObjectProperties() {
        return new SignedDataObjectProperties();
    }

    /**
     * Create an instance of {@link UnsignedDataObjectProperty }
     * 
     */
    public UnsignedDataObjectProperty createUnsignedDataObjectProperty() {
        return new UnsignedDataObjectProperty();
    }

    /**
     * Create an instance of {@link EncapsulatedTimeStamp }
     * 
     */
    public EncapsulatedTimeStamp createEncapsulatedTimeStamp() {
        return new EncapsulatedTimeStamp();
    }

    /**
     * Create an instance of {@link Issuer }
     * 
     */
    public Issuer createIssuer() {
        return new Issuer();
    }

    /**
     * Create an instance of {@link ResponderID }
     * 
     */
    public ResponderID createResponderID() {
        return new ResponderID();
    }

    /**
     * Create an instance of {@link NoticeNumbers }
     * 
     */
    public NoticeNumbers createNoticeNumbers() {
        return new NoticeNumbers();
    }

    /**
     * Create an instance of {@link PostalCode }
     * 
     */
    public PostalCode createPostalCode() {
        return new PostalCode();
    }

    /**
     * Create an instance of {@link Any }
     * 
     */
    public Any createAny() {
        return new Any();
    }

    /**
     * Create an instance of {@link UnsignedDataObjectProperties }
     * 
     */
    public UnsignedDataObjectProperties createUnsignedDataObjectProperties() {
        return new UnsignedDataObjectProperties();
    }

    /**
     * Create an instance of {@link SignerRole }
     * 
     */
    public SignerRole createSignerRole() {
        return new SignerRole();
    }

    /**
     * Create an instance of {@link ByName }
     * 
     */
    public ByName createByName() {
        return new ByName();
    }

    /**
     * Create an instance of {@link SigPolicyHash }
     * 
     */
    public SigPolicyHash createSigPolicyHash() {
        return new SigPolicyHash();
    }

    /**
     * Create an instance of {@link Number }
     * 
     */
    public Number createNumber() {
        return new Number();
    }

    /**
     * Create an instance of {@link SigningTime }
     * 
     */
    public SigningTime createSigningTime() {
        return new SigningTime();
    }

    /**
     * Create an instance of {@link RefsOnlyTimeStamp }
     * 
     */
    public RefsOnlyTimeStamp createRefsOnlyTimeStamp() {
        return new RefsOnlyTimeStamp();
    }

    /**
     * Create an instance of {@link AttrAuthoritiesCertValues }
     * 
     */
    public AttrAuthoritiesCertValues createAttrAuthoritiesCertValues() {
        return new AttrAuthoritiesCertValues();
    }

    /**
     * Create an instance of {@link NoticeRef }
     * 
     */
    public NoticeRef createNoticeRef() {
        return new NoticeRef();
    }

    /**
     * Create an instance of {@link SignaturePolicyId }
     * 
     */
    public SignaturePolicyId createSignaturePolicyId() {
        return new SignaturePolicyId();
    }

    /**
     * Create an instance of {@link CounterSignature }
     * 
     */
    public CounterSignature createCounterSignature() {
        return new CounterSignature();
    }

    /**
     * Create an instance of {@link CommitmentTypeQualifier }
     * 
     */
    public CommitmentTypeQualifier createCommitmentTypeQualifier() {
        return new CommitmentTypeQualifier();
    }

    /**
     * Create an instance of {@link Int }
     * 
     */
    public Int createInt() {
        return new Int();
    }

    /**
     * Create an instance of {@link SignedSignatureProperties }
     * 
     */
    public SignedSignatureProperties createSignedSignatureProperties() {
        return new SignedSignatureProperties();
    }

    /**
     * Create an instance of {@link ClaimedRole }
     * 
     */
    public ClaimedRole createClaimedRole() {
        return new ClaimedRole();
    }

    /**
     * Create an instance of {@link CertDigest }
     * 
     */
    public CertDigest createCertDigest() {
        return new CertDigest();
    }

    /**
     * Create an instance of {@link DataObjectFormat }
     * 
     */
    public DataObjectFormat createDataObjectFormat() {
        return new DataObjectFormat();
    }

    /**
     * Create an instance of {@link SigPolicyId }
     * 
     */
    public SigPolicyId createSigPolicyId() {
        return new SigPolicyId();
    }

    /**
     * Create an instance of {@link OCSPRefs }
     * 
     */
    public OCSPRefs createOCSPRefs() {
        return new OCSPRefs();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoticeRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "NoticeRef")
    public JAXBElement<NoticeRef> createNoticeRef(NoticeRef value) {
        return new JAXBElement<NoticeRef>(_NoticeRef_QNAME, NoticeRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CounterSignature }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CounterSignature")
    public JAXBElement<CounterSignature> createCounterSignature(CounterSignature value) {
        return new JAXBElement<CounterSignature>(_CounterSignature_QNAME, CounterSignature.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SigPolicyHash }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigPolicyHash")
    public JAXBElement<SigPolicyHash> createSigPolicyHash(SigPolicyHash value) {
        return new JAXBElement<SigPolicyHash>(_SigPolicyHash_QNAME, SigPolicyHash.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateOrProvince }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "StateOrProvince")
    public JAXBElement<StateOrProvince> createStateOrProvince(StateOrProvince value) {
        return new JAXBElement<StateOrProvince>(_StateOrProvince_QNAME, StateOrProvince.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Identifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Identifier")
    public JAXBElement<Identifier> createIdentifier(Identifier value) {
        return new JAXBElement<Identifier>(_Identifier_QNAME, Identifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCSPIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OCSPIdentifier")
    public JAXBElement<OCSPIdentifier> createOCSPIdentifier(OCSPIdentifier value) {
        return new JAXBElement<OCSPIdentifier>(_OCSPIdentifier_QNAME, OCSPIdentifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherValues }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OtherValues")
    public JAXBElement<OtherValues> createOtherValues(OtherValues value) {
        return new JAXBElement<OtherValues>(_OtherValues_QNAME, OtherValues.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignedProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignedProperties")
    public JAXBElement<SignedProperties> createSignedProperties(SignedProperties value) {
        return new JAXBElement<SignedProperties>(_SignedProperties_QNAME, SignedProperties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cert }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Cert")
    public JAXBElement<Cert> createCert(Cert value) {
        return new JAXBElement<Cert>(_Cert_QNAME, Cert.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AllDataObjectsTimeStamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AllDataObjectsTimeStamp")
    public JAXBElement<AllDataObjectsTimeStamp> createAllDataObjectsTimeStamp(AllDataObjectsTimeStamp value) {
        return new JAXBElement<AllDataObjectsTimeStamp>(_AllDataObjectsTimeStamp_QNAME, AllDataObjectsTimeStamp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPUserNotice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SPUserNotice")
    public JAXBElement<SPUserNotice> createSPUserNotice(SPUserNotice value) {
        return new JAXBElement<SPUserNotice>(_SPUserNotice_QNAME, SPUserNotice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OtherRefs")
    public JAXBElement<OtherRefs> createOtherRefs(OtherRefs value) {
        return new JAXBElement<OtherRefs>(_OtherRefs_QNAME, OtherRefs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeCertificateRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeCertificateRefs")
    public JAXBElement<AttributeCertificateRefs> createAttributeCertificateRefs(AttributeCertificateRefs value) {
        return new JAXBElement<AttributeCertificateRefs>(_AttributeCertificateRefs_QNAME, AttributeCertificateRefs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLTimeStamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "XMLTimeStamp")
    public JAXBElement<XMLTimeStamp> createXMLTimeStamp(XMLTimeStamp value) {
        return new JAXBElement<XMLTimeStamp>(_XMLTimeStamp_QNAME, XMLTimeStamp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommitmentTypeId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CommitmentTypeId")
    public JAXBElement<CommitmentTypeId> createCommitmentTypeId(CommitmentTypeId value) {
        return new JAXBElement<CommitmentTypeId>(_CommitmentTypeId_QNAME, CommitmentTypeId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncapsulatedCRLValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "EncapsulatedCRLValue")
    public JAXBElement<EncapsulatedCRLValue> createEncapsulatedCRLValue(EncapsulatedCRLValue value) {
        return new JAXBElement<EncapsulatedCRLValue>(_EncapsulatedCRLValue_QNAME, EncapsulatedCRLValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertDigest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CertDigest")
    public JAXBElement<CertDigest> createCertDigest(CertDigest value) {
        return new JAXBElement<CertDigest>(_CertDigest_QNAME, CertDigest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignaturePolicyId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignaturePolicyId")
    public JAXBElement<SignaturePolicyId> createSignaturePolicyId(SignaturePolicyId value) {
        return new JAXBElement<SignaturePolicyId>(_SignaturePolicyId_QNAME, SignaturePolicyId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Int }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "int")
    public JAXBElement<Int> createInt(Int value) {
        return new JAXBElement<Int>(_Int_QNAME, Int.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SigningTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigningTime")
    public JAXBElement<SigningTime> createSigningTime(SigningTime value) {
        return new JAXBElement<SigningTime>(_SigningTime_QNAME, SigningTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostalCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "PostalCode")
    public JAXBElement<PostalCode> createPostalCode(PostalCode value) {
        return new JAXBElement<PostalCode>(_PostalCode_QNAME, PostalCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignerRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignerRole")
    public JAXBElement<SignerRole> createSignerRole(SignerRole value) {
        return new JAXBElement<SignerRole>(_SignerRole_QNAME, SignerRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndividualDataObjectsTimeStamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "IndividualDataObjectsTimeStamp")
    public JAXBElement<IndividualDataObjectsTimeStamp> createIndividualDataObjectsTimeStamp(IndividualDataObjectsTimeStamp value) {
        return new JAXBElement<IndividualDataObjectsTimeStamp>(_IndividualDataObjectsTimeStamp_QNAME, IndividualDataObjectsTimeStamp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureProductionPlace }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignatureProductionPlace")
    public JAXBElement<SignatureProductionPlace> createSignatureProductionPlace(SignatureProductionPlace value) {
        return new JAXBElement<SignatureProductionPlace>(_SignatureProductionPlace_QNAME, SignatureProductionPlace.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnsignedSignatureProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "UnsignedSignatureProperties")
    public JAXBElement<UnsignedSignatureProperties> createUnsignedSignatureProperties(UnsignedSignatureProperties value) {
        return new JAXBElement<UnsignedSignatureProperties>(_UnsignedSignatureProperties_QNAME, UnsignedSignatureProperties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Include }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Include")
    public JAXBElement<Include> createInclude(Include value) {
        return new JAXBElement<Include>(_Include_QNAME, Include.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CRLRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CRLRef")
    public JAXBElement<CRLRef> createCRLRef(CRLRef value) {
        return new JAXBElement<CRLRef>(_CRLRef_QNAME, CRLRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SigAndRefsTimeStamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigAndRefsTimeStamp")
    public JAXBElement<SigAndRefsTimeStamp> createSigAndRefsTimeStamp(SigAndRefsTimeStamp value) {
        return new JAXBElement<SigAndRefsTimeStamp>(_SigAndRefsTimeStamp_QNAME, SigAndRefsTimeStamp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Description }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Description")
    public JAXBElement<Description> createDescription(Description value) {
        return new JAXBElement<Description>(_Description_QNAME, Description.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CRLIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CRLIdentifier")
    public JAXBElement<CRLIdentifier> createCRLIdentifier(CRLIdentifier value) {
        return new JAXBElement<CRLIdentifier>(_CRLIdentifier_QNAME, CRLIdentifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignaturePolicyIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignaturePolicyIdentifier")
    public JAXBElement<SignaturePolicyIdentifier> createSignaturePolicyIdentifier(SignaturePolicyIdentifier value) {
        return new JAXBElement<SignaturePolicyIdentifier>(_SignaturePolicyIdentifier_QNAME, SignaturePolicyIdentifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509SerialNumber }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "X509SerialNumber")
    public JAXBElement<X509SerialNumber> createX509SerialNumber(X509SerialNumber value) {
        return new JAXBElement<X509SerialNumber>(_X509SerialNumber_QNAME, X509SerialNumber.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SigPolicyQualifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigPolicyQualifier")
    public JAXBElement<SigPolicyQualifier> createSigPolicyQualifier(SigPolicyQualifier value) {
        return new JAXBElement<SigPolicyQualifier>(_SigPolicyQualifier_QNAME, SigPolicyQualifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommitmentTypeQualifiers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CommitmentTypeQualifiers")
    public JAXBElement<CommitmentTypeQualifiers> createCommitmentTypeQualifiers(CommitmentTypeQualifiers value) {
        return new JAXBElement<CommitmentTypeQualifiers>(_CommitmentTypeQualifiers_QNAME, CommitmentTypeQualifiers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OtherValue")
    public JAXBElement<OtherValue> createOtherValue(OtherValue value) {
        return new JAXBElement<OtherValue>(_OtherValue_QNAME, OtherValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignedSignatureProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignedSignatureProperties")
    public JAXBElement<SignedSignatureProperties> createSignedSignatureProperties(SignedSignatureProperties value) {
        return new JAXBElement<SignedSignatureProperties>(_SignedSignatureProperties_QNAME, SignedSignatureProperties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataObjectFormat }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "DataObjectFormat")
    public JAXBElement<DataObjectFormat> createDataObjectFormat(DataObjectFormat value) {
        return new JAXBElement<DataObjectFormat>(_DataObjectFormat_QNAME, DataObjectFormat.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClaimedRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ClaimedRole")
    public JAXBElement<ClaimedRole> createClaimedRole(ClaimedRole value) {
        return new JAXBElement<ClaimedRole>(_ClaimedRole_QNAME, ClaimedRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Number }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Number")
    public JAXBElement<Number> createNumber(Number value) {
        return new JAXBElement<Number>(_Number_QNAME, Number.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttrAuthoritiesCertValues }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttrAuthoritiesCertValues")
    public JAXBElement<AttrAuthoritiesCertValues> createAttrAuthoritiesCertValues(AttrAuthoritiesCertValues value) {
        return new JAXBElement<AttrAuthoritiesCertValues>(_AttrAuthoritiesCertValues_QNAME, AttrAuthoritiesCertValues.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnsignedDataObjectProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "UnsignedDataObjectProperty")
    public JAXBElement<UnsignedDataObjectProperty> createUnsignedDataObjectProperty(UnsignedDataObjectProperty value) {
        return new JAXBElement<UnsignedDataObjectProperty>(_UnsignedDataObjectProperty_QNAME, UnsignedDataObjectProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponderID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ResponderID")
    public JAXBElement<ResponderID> createResponderID(ResponderID value) {
        return new JAXBElement<ResponderID>(_ResponderID_QNAME, ResponderID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ByName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ByName")
    public JAXBElement<ByName> createByName(ByName value) {
        return new JAXBElement<ByName>(_ByName_QNAME, ByName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnsignedDataObjectProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "UnsignedDataObjectProperties")
    public JAXBElement<UnsignedDataObjectProperties> createUnsignedDataObjectProperties(UnsignedDataObjectProperties value) {
        return new JAXBElement<UnsignedDataObjectProperties>(_UnsignedDataObjectProperties_QNAME, UnsignedDataObjectProperties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Encoding }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Encoding")
    public JAXBElement<Encoding> createEncoding(Encoding value) {
        return new JAXBElement<Encoding>(_Encoding_QNAME, Encoding.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExplicitText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ExplicitText")
    public JAXBElement<ExplicitText> createExplicitText(ExplicitText value) {
        return new JAXBElement<ExplicitText>(_ExplicitText_QNAME, ExplicitText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherCertificate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OtherCertificate")
    public JAXBElement<OtherCertificate> createOtherCertificate(OtherCertificate value) {
        return new JAXBElement<OtherCertificate>(_OtherCertificate_QNAME, OtherCertificate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SigPolicyQualifiers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigPolicyQualifiers")
    public JAXBElement<SigPolicyQualifiers> createSigPolicyQualifiers(SigPolicyQualifiers value) {
        return new JAXBElement<SigPolicyQualifiers>(_SigPolicyQualifiers_QNAME, SigPolicyQualifiers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTimeStamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ArchiveTimeStamp")
    public JAXBElement<ArchiveTimeStamp> createArchiveTimeStamp(ArchiveTimeStamp value) {
        return new JAXBElement<ArchiveTimeStamp>(_ArchiveTimeStamp_QNAME, ArchiveTimeStamp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncapsulatedX509Certificate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "EncapsulatedX509Certificate")
    public JAXBElement<EncapsulatedX509Certificate> createEncapsulatedX509Certificate(EncapsulatedX509Certificate value) {
        return new JAXBElement<EncapsulatedX509Certificate>(_EncapsulatedX509Certificate_QNAME, EncapsulatedX509Certificate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteRevocationRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CompleteRevocationRefs")
    public JAXBElement<CompleteRevocationRefs> createCompleteRevocationRefs(CompleteRevocationRefs value) {
        return new JAXBElement<CompleteRevocationRefs>(_CompleteRevocationRefs_QNAME, CompleteRevocationRefs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AllSignedDataObjects }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AllSignedDataObjects")
    public JAXBElement<AllSignedDataObjects> createAllSignedDataObjects(AllSignedDataObjects value) {
        return new JAXBElement<AllSignedDataObjects>(_AllSignedDataObjects_QNAME, AllSignedDataObjects.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeRevocationValues }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeRevocationValues")
    public JAXBElement<AttributeRevocationValues> createAttributeRevocationValues(AttributeRevocationValues value) {
        return new JAXBElement<AttributeRevocationValues>(_AttributeRevocationValues_QNAME, AttributeRevocationValues.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertificateValues }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CertificateValues")
    public JAXBElement<CertificateValues> createCertificateValues(CertificateValues value) {
        return new JAXBElement<CertificateValues>(_CertificateValues_QNAME, CertificateValues.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevocationValues }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "RevocationValues")
    public JAXBElement<RevocationValues> createRevocationValues(RevocationValues value) {
        return new JAXBElement<RevocationValues>(_RevocationValues_QNAME, RevocationValues.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteCertificateRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CompleteCertificateRefs")
    public JAXBElement<CompleteCertificateRefs> createCompleteCertificateRefs(CompleteCertificateRefs value) {
        return new JAXBElement<CompleteCertificateRefs>(_CompleteCertificateRefs_QNAME, CompleteCertificateRefs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureTimeStamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignatureTimeStamp")
    public JAXBElement<SignatureTimeStamp> createSignatureTimeStamp(SignatureTimeStamp value) {
        return new JAXBElement<SignatureTimeStamp>(_SignatureTimeStamp_QNAME, SignatureTimeStamp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeRevocationRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "AttributeRevocationRefs")
    public JAXBElement<AttributeRevocationRefs> createAttributeRevocationRefs(AttributeRevocationRefs value) {
        return new JAXBElement<AttributeRevocationRefs>(_AttributeRevocationRefs_QNAME, AttributeRevocationRefs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ObjectReference")
    public JAXBElement<ObjectReference> createObjectReference(ObjectReference value) {
        return new JAXBElement<ObjectReference>(_ObjectReference_QNAME, ObjectReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignaturePolicyImplied }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignaturePolicyImplied")
    public JAXBElement<SignaturePolicyImplied> createSignaturePolicyImplied(SignaturePolicyImplied value) {
        return new JAXBElement<SignaturePolicyImplied>(_SignaturePolicyImplied_QNAME, SignaturePolicyImplied.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ObjectIdentifier")
    public JAXBElement<ObjectIdentifier> createObjectIdentifier(ObjectIdentifier value) {
        return new JAXBElement<ObjectIdentifier>(_ObjectIdentifier_QNAME, ObjectIdentifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertifiedRoles }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CertifiedRoles")
    public JAXBElement<CertifiedRoles> createCertifiedRoles(CertifiedRoles value) {
        return new JAXBElement<CertifiedRoles>(_CertifiedRoles_QNAME, CertifiedRoles.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IssuerSerial }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "IssuerSerial")
    public JAXBElement<IssuerSerial> createIssuerSerial(IssuerSerial value) {
        return new JAXBElement<IssuerSerial>(_IssuerSerial_QNAME, IssuerSerial.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509IssuerName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "X509IssuerName")
    public JAXBElement<X509IssuerName> createX509IssuerName(X509IssuerName value) {
        return new JAXBElement<X509IssuerName>(_X509IssuerName_QNAME, X509IssuerName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountryName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CountryName")
    public JAXBElement<CountryName> createCountryName(CountryName value) {
        return new JAXBElement<CountryName>(_CountryName_QNAME, CountryName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SigningCertificate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigningCertificate")
    public JAXBElement<SigningCertificate> createSigningCertificate(SigningCertificate value) {
        return new JAXBElement<SigningCertificate>(_SigningCertificate_QNAME, SigningCertificate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SigPolicyId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SigPolicyId")
    public JAXBElement<SigPolicyId> createSigPolicyId(SigPolicyId value) {
        return new JAXBElement<SigPolicyId>(_SigPolicyId_QNAME, SigPolicyId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCSPRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OCSPRefs")
    public JAXBElement<OCSPRefs> createOCSPRefs(OCSPRefs value) {
        return new JAXBElement<OCSPRefs>(_OCSPRefs_QNAME, OCSPRefs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommitmentTypeQualifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CommitmentTypeQualifier")
    public JAXBElement<CommitmentTypeQualifier> createCommitmentTypeQualifier(CommitmentTypeQualifier value) {
        return new JAXBElement<CommitmentTypeQualifier>(_CommitmentTypeQualifier_QNAME, CommitmentTypeQualifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefsOnlyTimeStamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "RefsOnlyTimeStamp")
    public JAXBElement<RefsOnlyTimeStamp> createRefsOnlyTimeStamp(RefsOnlyTimeStamp value) {
        return new JAXBElement<RefsOnlyTimeStamp>(_RefsOnlyTimeStamp_QNAME, RefsOnlyTimeStamp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignedDataObjectProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SignedDataObjectProperties")
    public JAXBElement<SignedDataObjectProperties> createSignedDataObjectProperties(SignedDataObjectProperties value) {
        return new JAXBElement<SignedDataObjectProperties>(_SignedDataObjectProperties_QNAME, SignedDataObjectProperties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncapsulatedTimeStamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "EncapsulatedTimeStamp")
    public JAXBElement<EncapsulatedTimeStamp> createEncapsulatedTimeStamp(EncapsulatedTimeStamp value) {
        return new JAXBElement<EncapsulatedTimeStamp>(_EncapsulatedTimeStamp_QNAME, EncapsulatedTimeStamp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Issuer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Issuer")
    public JAXBElement<Issuer> createIssuer(Issuer value) {
        return new JAXBElement<Issuer>(_Issuer_QNAME, Issuer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoticeNumbers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "NoticeNumbers")
    public JAXBElement<NoticeNumbers> createNoticeNumbers(NoticeNumbers value) {
        return new JAXBElement<NoticeNumbers>(_NoticeNumbers_QNAME, NoticeNumbers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Any }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Any")
    public JAXBElement<Any> createAny(Any value) {
        return new JAXBElement<Any>(_Any_QNAME, Any.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ByKey }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ByKey")
    public JAXBElement<ByKey> createByKey(ByKey value) {
        return new JAXBElement<ByKey>(_ByKey_QNAME, ByKey.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProducedAt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ProducedAt")
    public JAXBElement<ProducedAt> createProducedAt(ProducedAt value) {
        return new JAXBElement<ProducedAt>(_ProducedAt_QNAME, ProducedAt.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCSPRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OCSPRef")
    public JAXBElement<OCSPRef> createOCSPRef(OCSPRef value) {
        return new JAXBElement<OCSPRef>(_OCSPRef_QNAME, OCSPRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncapsulatedPKIData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "EncapsulatedPKIData")
    public JAXBElement<EncapsulatedPKIData> createEncapsulatedPKIData(EncapsulatedPKIData value) {
        return new JAXBElement<EncapsulatedPKIData>(_EncapsulatedPKIData_QNAME, EncapsulatedPKIData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link City }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "City")
    public JAXBElement<City> createCity(City value) {
        return new JAXBElement<City>(_City_QNAME, City.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnsignedProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "UnsignedProperties")
    public JAXBElement<UnsignedProperties> createUnsignedProperties(UnsignedProperties value) {
        return new JAXBElement<UnsignedProperties>(_UnsignedProperties_QNAME, UnsignedProperties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CRLValues }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CRLValues")
    public JAXBElement<CRLValues> createCRLValues(CRLValues value) {
        return new JAXBElement<CRLValues>(_CRLValues_QNAME, CRLValues.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncapsulatedOCSPValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "EncapsulatedOCSPValue")
    public JAXBElement<EncapsulatedOCSPValue> createEncapsulatedOCSPValue(EncapsulatedOCSPValue value) {
        return new JAXBElement<EncapsulatedOCSPValue>(_EncapsulatedOCSPValue_QNAME, EncapsulatedOCSPValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OtherRef")
    public JAXBElement<OtherRef> createOtherRef(OtherRef value) {
        return new JAXBElement<OtherRef>(_OtherRef_QNAME, OtherRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CertRefs")
    public JAXBElement<CertRefs> createCertRefs(CertRefs value) {
        return new JAXBElement<CertRefs>(_CertRefs_QNAME, CertRefs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPURI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "SPURI")
    public JAXBElement<SPURI> createSPURI(SPURI value) {
        return new JAXBElement<SPURI>(_SPURI_QNAME, SPURI.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ReferenceInfo")
    public JAXBElement<ReferenceInfo> createReferenceInfo(ReferenceInfo value) {
        return new JAXBElement<ReferenceInfo>(_ReferenceInfo_QNAME, ReferenceInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OCSPValues }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OCSPValues")
    public JAXBElement<OCSPValues> createOCSPValues(OCSPValues value) {
        return new JAXBElement<OCSPValues>(_OCSPValues_QNAME, OCSPValues.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommitmentTypeIndication }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CommitmentTypeIndication")
    public JAXBElement<CommitmentTypeIndication> createCommitmentTypeIndication(CommitmentTypeIndication value) {
        return new JAXBElement<CommitmentTypeIndication>(_CommitmentTypeIndication_QNAME, CommitmentTypeIndication.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifyingProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "QualifyingProperties")
    public JAXBElement<QualifyingProperties> createQualifyingProperties(QualifyingProperties value) {
        return new JAXBElement<QualifyingProperties>(_QualifyingProperties_QNAME, QualifyingProperties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertifiedRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CertifiedRole")
    public JAXBElement<CertifiedRole> createCertifiedRole(CertifiedRole value) {
        return new JAXBElement<CertifiedRole>(_CertifiedRole_QNAME, CertifiedRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IssueTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "IssueTime")
    public JAXBElement<IssueTime> createIssueTime(IssueTime value) {
        return new JAXBElement<IssueTime>(_IssueTime_QNAME, IssueTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Organization }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "Organization")
    public JAXBElement<Organization> createOrganization(Organization value) {
        return new JAXBElement<Organization>(_Organization_QNAME, Organization.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentationReferences }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "DocumentationReferences")
    public JAXBElement<DocumentationReferences> createDocumentationReferences(DocumentationReferences value) {
        return new JAXBElement<DocumentationReferences>(_DocumentationReferences_QNAME, DocumentationReferences.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DigestAlgAndValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "DigestAlgAndValue")
    public JAXBElement<DigestAlgAndValue> createDigestAlgAndValue(DigestAlgAndValue value) {
        return new JAXBElement<DigestAlgAndValue>(_DigestAlgAndValue_QNAME, DigestAlgAndValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MimeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "MimeType")
    public JAXBElement<MimeType> createMimeType(MimeType value) {
        return new JAXBElement<MimeType>(_MimeType_QNAME, MimeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClaimedRoles }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "ClaimedRoles")
    public JAXBElement<ClaimedRoles> createClaimedRoles(ClaimedRoles value) {
        return new JAXBElement<ClaimedRoles>(_ClaimedRoles_QNAME, ClaimedRoles.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XAdESTimeStamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "XAdESTimeStamp")
    public JAXBElement<XAdESTimeStamp> createXAdESTimeStamp(XAdESTimeStamp value) {
        return new JAXBElement<XAdESTimeStamp>(_XAdESTimeStamp_QNAME, XAdESTimeStamp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CRLRefs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "CRLRefs")
    public JAXBElement<CRLRefs> createCRLRefs(CRLRefs value) {
        return new JAXBElement<CRLRefs>(_CRLRefs_QNAME, CRLRefs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentationReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "DocumentationReference")
    public JAXBElement<DocumentationReference> createDocumentationReference(DocumentationReference value) {
        return new JAXBElement<DocumentationReference>(_DocumentationReference_QNAME, DocumentationReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OtherTimeStamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "OtherTimeStamp")
    public JAXBElement<OtherTimeStamp> createOtherTimeStamp(OtherTimeStamp value) {
        return new JAXBElement<OtherTimeStamp>(_OtherTimeStamp_QNAME, OtherTimeStamp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifyingPropertiesReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://uri.etsi.org/01903/v1.3.2#", name = "QualifyingPropertiesReference")
    public JAXBElement<QualifyingPropertiesReference> createQualifyingPropertiesReference(QualifyingPropertiesReference value) {
        return new JAXBElement<QualifyingPropertiesReference>(_QualifyingPropertiesReference_QNAME, QualifyingPropertiesReference.class, null, value);
    }

}
