//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.04 at 05:24:23 PM EDT 
//


package org.etsi.uri._01903.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponderID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponderID">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}ByName"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}ByKey"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponderID", namespace = "http://uri.etsi.org/01903/v1.3.2#", propOrder = {
    "byName",
    "byKey"
})
public class ResponderID {

    @XmlElement(name = "ByName", namespace = "http://uri.etsi.org/01903/v1.3.2#")
    protected ByName byName;
    @XmlElement(name = "ByKey", namespace = "http://uri.etsi.org/01903/v1.3.2#")
    protected ByKey byKey;

    /**
     * Gets the value of the byName property.
     * 
     * @return
     *     possible object is
     *     {@link ByName }
     *     
     */
    public ByName getByName() {
        return byName;
    }

    /**
     * Sets the value of the byName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ByName }
     *     
     */
    public void setByName(ByName value) {
        this.byName = value;
    }

    /**
     * Gets the value of the byKey property.
     * 
     * @return
     *     possible object is
     *     {@link ByKey }
     *     
     */
    public ByKey getByKey() {
        return byKey;
    }

    /**
     * Sets the value of the byKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link ByKey }
     *     
     */
    public void setByKey(ByKey value) {
        this.byKey = value;
    }

}
