//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.04 at 05:24:23 PM EDT 
//


package org.etsi.uri._01903.v1_3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SPUserNotice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SPUserNotice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}NoticeRef" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}ExplicitText" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPUserNotice", namespace = "http://uri.etsi.org/01903/v1.3.2#", propOrder = {
    "noticeRef",
    "explicitText"
})
public class SPUserNotice {

    @XmlElement(name = "NoticeRef", namespace = "http://uri.etsi.org/01903/v1.3.2#")
    protected NoticeRef noticeRef;
    @XmlElement(name = "ExplicitText", namespace = "http://uri.etsi.org/01903/v1.3.2#")
    protected ExplicitText explicitText;

    /**
     * Gets the value of the noticeRef property.
     * 
     * @return
     *     possible object is
     *     {@link NoticeRef }
     *     
     */
    public NoticeRef getNoticeRef() {
        return noticeRef;
    }

    /**
     * Sets the value of the noticeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoticeRef }
     *     
     */
    public void setNoticeRef(NoticeRef value) {
        this.noticeRef = value;
    }

    /**
     * Gets the value of the explicitText property.
     * 
     * @return
     *     possible object is
     *     {@link ExplicitText }
     *     
     */
    public ExplicitText getExplicitText() {
        return explicitText;
    }

    /**
     * Sets the value of the explicitText property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExplicitText }
     *     
     */
    public void setExplicitText(ExplicitText value) {
        this.explicitText = value;
    }

}
