//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.04 at 05:24:23 PM EDT 
//


package org.etsi.uri._01903.v1_3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for UnsignedSignatureProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnsignedSignatureProperties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}CounterSignature"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}SignatureTimeStamp"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}CompleteCertificateRefs"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}CompleteRevocationRefs"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}AttributeCertificateRefs"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}AttributeRevocationRefs"/>
 *         &lt;choice>
 *           &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}SigAndRefsTimeStamp"/>
 *           &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}RefsOnlyTimeStamp"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}CertificateValues"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}RevocationValues"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}AttrAuthoritiesCertValues"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}AttributeRevocationValues"/>
 *         &lt;element ref="{http://uri.etsi.org/01903/v1.3.2#}ArchiveTimeStamp"/>
 *       &lt;/choice>
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnsignedSignatureProperties", namespace = "http://uri.etsi.org/01903/v1.3.2#", propOrder = {
    "counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs"
})
public class UnsignedSignatureProperties {

    @XmlElements({
        @XmlElement(name = "CounterSignature", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = CounterSignature.class),
        @XmlElement(name = "SignatureTimeStamp", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = SignatureTimeStamp.class),
        @XmlElement(name = "CompleteCertificateRefs", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = CompleteCertificateRefs.class),
        @XmlElement(name = "CompleteRevocationRefs", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = CompleteRevocationRefs.class),
        @XmlElement(name = "AttributeCertificateRefs", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = AttributeCertificateRefs.class),
        @XmlElement(name = "AttributeRevocationRefs", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = AttributeRevocationRefs.class),
        @XmlElement(name = "SigAndRefsTimeStamp", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = SigAndRefsTimeStamp.class),
        @XmlElement(name = "RefsOnlyTimeStamp", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = RefsOnlyTimeStamp.class),
        @XmlElement(name = "CertificateValues", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = CertificateValues.class),
        @XmlElement(name = "RevocationValues", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = RevocationValues.class),
        @XmlElement(name = "AttrAuthoritiesCertValues", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = AttrAuthoritiesCertValues.class),
        @XmlElement(name = "AttributeRevocationValues", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = AttributeRevocationValues.class),
        @XmlElement(name = "ArchiveTimeStamp", namespace = "http://uri.etsi.org/01903/v1.3.2#", type = ArchiveTimeStamp.class)
    })
    protected List<Object> counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs;
    @XmlAttribute(name = "Id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCounterSignatureOrSignatureTimeStampOrCompleteCertificateRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CounterSignature }
     * {@link SignatureTimeStamp }
     * {@link CompleteCertificateRefs }
     * {@link CompleteRevocationRefs }
     * {@link AttributeCertificateRefs }
     * {@link AttributeRevocationRefs }
     * {@link SigAndRefsTimeStamp }
     * {@link RefsOnlyTimeStamp }
     * {@link CertificateValues }
     * {@link RevocationValues }
     * {@link AttrAuthoritiesCertValues }
     * {@link AttributeRevocationValues }
     * {@link ArchiveTimeStamp }
     * 
     * 
     */
    public List<Object> getCounterSignatureOrSignatureTimeStampOrCompleteCertificateRefs() {
        if (counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs == null) {
            counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs = new ArrayList<Object>();
        }
        return this.counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
