//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.04 at 05:24:23 PM EDT 
//


package org.w3._2000._09.xmldsig_;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2000._09.xmldsig_ package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SignatureProperty_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureProperty");
    private final static QName _RSAKeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "RSAKeyValue");
    private final static QName _SignatureMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureMethod");
    private final static QName _Object_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Object");
    private final static QName _X509SerialNumber_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509SerialNumber");
    private final static QName _RetrievalMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "RetrievalMethod");
    private final static QName _KeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyValue");
    private final static QName _SignatureProperties_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureProperties");
    private final static QName _Reference_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Reference");
    private final static QName _Exponent_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Exponent");
    private final static QName _PgenCounter_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PgenCounter");
    private final static QName _KeyName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyName");
    private final static QName _Signature_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Signature");
    private final static QName _MgmtData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "MgmtData");
    private final static QName _CanonicalizationMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "CanonicalizationMethod");
    private final static QName _HMACOutputLength_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "HMACOutputLength");
    private final static QName _X509CRL_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509CRL");
    private final static QName _PGPKeyPacket_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPKeyPacket");
    private final static QName _SignatureValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureValue");
    private final static QName _SignedInfo_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignedInfo");
    private final static QName _Seed_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Seed");
    private final static QName _DigestMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DigestMethod");
    private final static QName _X509IssuerSerial_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509IssuerSerial");
    private final static QName _KeyInfo_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyInfo");
    private final static QName _PGPKeyID_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPKeyID");
    private final static QName _Modulus_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Modulus");
    private final static QName _PGPData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPData");
    private final static QName _DSAKeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DSAKeyValue");
    private final static QName _X509Certificate_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509Certificate");
    private final static QName _Transforms_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Transforms");
    private final static QName _Transform_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Transform");
    private final static QName _DigestValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DigestValue");
    private final static QName _X509SKI_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509SKI");
    private final static QName _SPKISexp_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SPKISexp");
    private final static QName _Manifest_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Manifest");
    private final static QName _Q_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Q");
    private final static QName _P_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "P");
    private final static QName _Y_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Y");
    private final static QName _G_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "G");
    private final static QName _X509IssuerName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509IssuerName");
    private final static QName _J_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "J");
    private final static QName _X509Data_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509Data");
    private final static QName _XPath_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "XPath");
    private final static QName _X509SubjectName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509SubjectName");
    private final static QName _SPKIData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SPKIData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2000._09.xmldsig_
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KeyValue }
     * 
     */
    public KeyValue createKeyValue() {
        return new KeyValue();
    }

    /**
     * Create an instance of {@link X509CRL }
     * 
     */
    public X509CRL createX509CRL() {
        return new X509CRL();
    }

    /**
     * Create an instance of {@link Exponent }
     * 
     */
    public Exponent createExponent() {
        return new Exponent();
    }

    /**
     * Create an instance of {@link X509IssuerName }
     * 
     */
    public X509IssuerName createX509IssuerName() {
        return new X509IssuerName();
    }

    /**
     * Create an instance of {@link Transforms }
     * 
     */
    public Transforms createTransforms() {
        return new Transforms();
    }

    /**
     * Create an instance of {@link G }
     * 
     */
    public G createG() {
        return new G();
    }

    /**
     * Create an instance of {@link PgenCounter }
     * 
     */
    public PgenCounter createPgenCounter() {
        return new PgenCounter();
    }

    /**
     * Create an instance of {@link J }
     * 
     */
    public J createJ() {
        return new J();
    }

    /**
     * Create an instance of {@link DigestMethod }
     * 
     */
    public DigestMethod createDigestMethod() {
        return new DigestMethod();
    }

    /**
     * Create an instance of {@link SignatureProperty }
     * 
     */
    public SignatureProperty createSignatureProperty() {
        return new SignatureProperty();
    }

    /**
     * Create an instance of {@link X509Data }
     * 
     */
    public X509Data createX509Data() {
        return new X509Data();
    }

    /**
     * Create an instance of {@link PGPKeyID }
     * 
     */
    public PGPKeyID createPGPKeyID() {
        return new PGPKeyID();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link SPKIData }
     * 
     */
    public SPKIData createSPKIData() {
        return new SPKIData();
    }

    /**
     * Create an instance of {@link HMACOutputLength }
     * 
     */
    public HMACOutputLength createHMACOutputLength() {
        return new HMACOutputLength();
    }

    /**
     * Create an instance of {@link Q }
     * 
     */
    public Q createQ() {
        return new Q();
    }

    /**
     * Create an instance of {@link X509IssuerSerial }
     * 
     */
    public X509IssuerSerial createX509IssuerSerial() {
        return new X509IssuerSerial();
    }

    /**
     * Create an instance of {@link SignatureValue }
     * 
     */
    public SignatureValue createSignatureValue() {
        return new SignatureValue();
    }

    /**
     * Create an instance of {@link KeyInfo }
     * 
     */
    public KeyInfo createKeyInfo() {
        return new KeyInfo();
    }

    /**
     * Create an instance of {@link Y }
     * 
     */
    public Y createY() {
        return new Y();
    }

    /**
     * Create an instance of {@link X509SKI }
     * 
     */
    public X509SKI createX509SKI() {
        return new X509SKI();
    }

    /**
     * Create an instance of {@link XPath }
     * 
     */
    public XPath createXPath() {
        return new XPath();
    }

    /**
     * Create an instance of {@link PGPData }
     * 
     */
    public PGPData createPGPData() {
        return new PGPData();
    }

    /**
     * Create an instance of {@link DSAKeyValue }
     * 
     */
    public DSAKeyValue createDSAKeyValue() {
        return new DSAKeyValue();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link RetrievalMethod }
     * 
     */
    public RetrievalMethod createRetrievalMethod() {
        return new RetrievalMethod();
    }

    /**
     * Create an instance of {@link CanonicalizationMethod }
     * 
     */
    public CanonicalizationMethod createCanonicalizationMethod() {
        return new CanonicalizationMethod();
    }

    /**
     * Create an instance of {@link DigestValue }
     * 
     */
    public DigestValue createDigestValue() {
        return new DigestValue();
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link PGPKeyPacket }
     * 
     */
    public PGPKeyPacket createPGPKeyPacket() {
        return new PGPKeyPacket();
    }

    /**
     * Create an instance of {@link X509Certificate }
     * 
     */
    public X509Certificate createX509Certificate() {
        return new X509Certificate();
    }

    /**
     * Create an instance of {@link SignedInfo }
     * 
     */
    public SignedInfo createSignedInfo() {
        return new SignedInfo();
    }

    /**
     * Create an instance of {@link KeyName }
     * 
     */
    public KeyName createKeyName() {
        return new KeyName();
    }

    /**
     * Create an instance of {@link RSAKeyValue }
     * 
     */
    public RSAKeyValue createRSAKeyValue() {
        return new RSAKeyValue();
    }

    /**
     * Create an instance of {@link MgmtData }
     * 
     */
    public MgmtData createMgmtData() {
        return new MgmtData();
    }

    /**
     * Create an instance of {@link Seed }
     * 
     */
    public Seed createSeed() {
        return new Seed();
    }

    /**
     * Create an instance of {@link Modulus }
     * 
     */
    public Modulus createModulus() {
        return new Modulus();
    }

    /**
     * Create an instance of {@link Signature }
     * 
     */
    public Signature createSignature() {
        return new Signature();
    }

    /**
     * Create an instance of {@link SignatureProperties }
     * 
     */
    public SignatureProperties createSignatureProperties() {
        return new SignatureProperties();
    }

    /**
     * Create an instance of {@link X509SubjectName }
     * 
     */
    public X509SubjectName createX509SubjectName() {
        return new X509SubjectName();
    }

    /**
     * Create an instance of {@link SignatureMethod }
     * 
     */
    public SignatureMethod createSignatureMethod() {
        return new SignatureMethod();
    }

    /**
     * Create an instance of {@link Object }
     * 
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link Transform }
     * 
     */
    public Transform createTransform() {
        return new Transform();
    }

    /**
     * Create an instance of {@link X509SerialNumber }
     * 
     */
    public X509SerialNumber createX509SerialNumber() {
        return new X509SerialNumber();
    }

    /**
     * Create an instance of {@link SPKISexp }
     * 
     */
    public SPKISexp createSPKISexp() {
        return new SPKISexp();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureProperty")
    public JAXBElement<SignatureProperty> createSignatureProperty(SignatureProperty value) {
        return new JAXBElement<SignatureProperty>(_SignatureProperty_QNAME, SignatureProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RSAKeyValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "RSAKeyValue")
    public JAXBElement<RSAKeyValue> createRSAKeyValue(RSAKeyValue value) {
        return new JAXBElement<RSAKeyValue>(_RSAKeyValue_QNAME, RSAKeyValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureMethod }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureMethod")
    public JAXBElement<SignatureMethod> createSignatureMethod(SignatureMethod value) {
        return new JAXBElement<SignatureMethod>(_SignatureMethod_QNAME, SignatureMethod.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Object")
    public JAXBElement<Object> createObject(Object value) {
        return new JAXBElement<Object>(_Object_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509SerialNumber }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509SerialNumber")
    public JAXBElement<X509SerialNumber> createX509SerialNumber(X509SerialNumber value) {
        return new JAXBElement<X509SerialNumber>(_X509SerialNumber_QNAME, X509SerialNumber.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrievalMethod }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "RetrievalMethod")
    public JAXBElement<RetrievalMethod> createRetrievalMethod(RetrievalMethod value) {
        return new JAXBElement<RetrievalMethod>(_RetrievalMethod_QNAME, RetrievalMethod.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyValue")
    public JAXBElement<KeyValue> createKeyValue(KeyValue value) {
        return new JAXBElement<KeyValue>(_KeyValue_QNAME, KeyValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureProperties")
    public JAXBElement<SignatureProperties> createSignatureProperties(SignatureProperties value) {
        return new JAXBElement<SignatureProperties>(_SignatureProperties_QNAME, SignatureProperties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Reference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Reference")
    public JAXBElement<Reference> createReference(Reference value) {
        return new JAXBElement<Reference>(_Reference_QNAME, Reference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exponent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Exponent")
    public JAXBElement<Exponent> createExponent(Exponent value) {
        return new JAXBElement<Exponent>(_Exponent_QNAME, Exponent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PgenCounter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PgenCounter")
    public JAXBElement<PgenCounter> createPgenCounter(PgenCounter value) {
        return new JAXBElement<PgenCounter>(_PgenCounter_QNAME, PgenCounter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyName")
    public JAXBElement<KeyName> createKeyName(KeyName value) {
        return new JAXBElement<KeyName>(_KeyName_QNAME, KeyName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Signature }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Signature")
    public JAXBElement<Signature> createSignature(Signature value) {
        return new JAXBElement<Signature>(_Signature_QNAME, Signature.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MgmtData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "MgmtData")
    public JAXBElement<MgmtData> createMgmtData(MgmtData value) {
        return new JAXBElement<MgmtData>(_MgmtData_QNAME, MgmtData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CanonicalizationMethod }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "CanonicalizationMethod")
    public JAXBElement<CanonicalizationMethod> createCanonicalizationMethod(CanonicalizationMethod value) {
        return new JAXBElement<CanonicalizationMethod>(_CanonicalizationMethod_QNAME, CanonicalizationMethod.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HMACOutputLength }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "HMACOutputLength")
    public JAXBElement<HMACOutputLength> createHMACOutputLength(HMACOutputLength value) {
        return new JAXBElement<HMACOutputLength>(_HMACOutputLength_QNAME, HMACOutputLength.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509CRL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509CRL")
    public JAXBElement<X509CRL> createX509CRL(X509CRL value) {
        return new JAXBElement<X509CRL>(_X509CRL_QNAME, X509CRL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PGPKeyPacket }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPKeyPacket")
    public JAXBElement<PGPKeyPacket> createPGPKeyPacket(PGPKeyPacket value) {
        return new JAXBElement<PGPKeyPacket>(_PGPKeyPacket_QNAME, PGPKeyPacket.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureValue")
    public JAXBElement<SignatureValue> createSignatureValue(SignatureValue value) {
        return new JAXBElement<SignatureValue>(_SignatureValue_QNAME, SignatureValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignedInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignedInfo")
    public JAXBElement<SignedInfo> createSignedInfo(SignedInfo value) {
        return new JAXBElement<SignedInfo>(_SignedInfo_QNAME, SignedInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Seed }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Seed")
    public JAXBElement<Seed> createSeed(Seed value) {
        return new JAXBElement<Seed>(_Seed_QNAME, Seed.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DigestMethod }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DigestMethod")
    public JAXBElement<DigestMethod> createDigestMethod(DigestMethod value) {
        return new JAXBElement<DigestMethod>(_DigestMethod_QNAME, DigestMethod.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509IssuerSerial }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509IssuerSerial")
    public JAXBElement<X509IssuerSerial> createX509IssuerSerial(X509IssuerSerial value) {
        return new JAXBElement<X509IssuerSerial>(_X509IssuerSerial_QNAME, X509IssuerSerial.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyInfo")
    public JAXBElement<KeyInfo> createKeyInfo(KeyInfo value) {
        return new JAXBElement<KeyInfo>(_KeyInfo_QNAME, KeyInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PGPKeyID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPKeyID")
    public JAXBElement<PGPKeyID> createPGPKeyID(PGPKeyID value) {
        return new JAXBElement<PGPKeyID>(_PGPKeyID_QNAME, PGPKeyID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Modulus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Modulus")
    public JAXBElement<Modulus> createModulus(Modulus value) {
        return new JAXBElement<Modulus>(_Modulus_QNAME, Modulus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PGPData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPData")
    public JAXBElement<PGPData> createPGPData(PGPData value) {
        return new JAXBElement<PGPData>(_PGPData_QNAME, PGPData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DSAKeyValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DSAKeyValue")
    public JAXBElement<DSAKeyValue> createDSAKeyValue(DSAKeyValue value) {
        return new JAXBElement<DSAKeyValue>(_DSAKeyValue_QNAME, DSAKeyValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509Certificate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509Certificate")
    public JAXBElement<X509Certificate> createX509Certificate(X509Certificate value) {
        return new JAXBElement<X509Certificate>(_X509Certificate_QNAME, X509Certificate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Transforms }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Transforms")
    public JAXBElement<Transforms> createTransforms(Transforms value) {
        return new JAXBElement<Transforms>(_Transforms_QNAME, Transforms.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Transform }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Transform")
    public JAXBElement<Transform> createTransform(Transform value) {
        return new JAXBElement<Transform>(_Transform_QNAME, Transform.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DigestValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DigestValue")
    public JAXBElement<DigestValue> createDigestValue(DigestValue value) {
        return new JAXBElement<DigestValue>(_DigestValue_QNAME, DigestValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509SKI }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509SKI")
    public JAXBElement<X509SKI> createX509SKI(X509SKI value) {
        return new JAXBElement<X509SKI>(_X509SKI_QNAME, X509SKI.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPKISexp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SPKISexp")
    public JAXBElement<SPKISexp> createSPKISexp(SPKISexp value) {
        return new JAXBElement<SPKISexp>(_SPKISexp_QNAME, SPKISexp.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Manifest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Manifest")
    public JAXBElement<Manifest> createManifest(Manifest value) {
        return new JAXBElement<Manifest>(_Manifest_QNAME, Manifest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Q }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Q")
    public JAXBElement<Q> createQ(Q value) {
        return new JAXBElement<Q>(_Q_QNAME, Q.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "P")
    public JAXBElement<P> createP(P value) {
        return new JAXBElement<P>(_P_QNAME, P.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Y }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Y")
    public JAXBElement<Y> createY(Y value) {
        return new JAXBElement<Y>(_Y_QNAME, Y.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link G }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "G")
    public JAXBElement<G> createG(G value) {
        return new JAXBElement<G>(_G_QNAME, G.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509IssuerName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509IssuerName")
    public JAXBElement<X509IssuerName> createX509IssuerName(X509IssuerName value) {
        return new JAXBElement<X509IssuerName>(_X509IssuerName_QNAME, X509IssuerName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link J }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "J")
    public JAXBElement<J> createJ(J value) {
        return new JAXBElement<J>(_J_QNAME, J.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509Data }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509Data")
    public JAXBElement<X509Data> createX509Data(X509Data value) {
        return new JAXBElement<X509Data>(_X509Data_QNAME, X509Data.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XPath }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "XPath")
    public JAXBElement<XPath> createXPath(XPath value) {
        return new JAXBElement<XPath>(_XPath_QNAME, XPath.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509SubjectName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509SubjectName")
    public JAXBElement<X509SubjectName> createX509SubjectName(X509SubjectName value) {
        return new JAXBElement<X509SubjectName>(_X509SubjectName_QNAME, X509SubjectName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPKIData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SPKIData")
    public JAXBElement<SPKIData> createSPKIData(SPKIData value) {
        return new JAXBElement<SPKIData>(_SPKIData_QNAME, SPKIData.class, null, value);
    }

}
