//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.04 at 05:24:23 PM EDT 
//


package org.w3._2000._09.xmldsig_;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SPKIData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SPKIData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}SPKISexp"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPKIData", namespace = "http://www.w3.org/2000/09/xmldsig#", propOrder = {
    "spkiSexp"
})
public class SPKIData {

    @XmlElement(name = "SPKISexp", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SPKISexp spkiSexp;

    /**
     * Gets the value of the spkiSexp property.
     * 
     * @return
     *     possible object is
     *     {@link SPKISexp }
     *     
     */
    public SPKISexp getSPKISexp() {
        return spkiSexp;
    }

    /**
     * Sets the value of the spkiSexp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPKISexp }
     *     
     */
    public void setSPKISexp(SPKISexp value) {
        this.spkiSexp = value;
    }

}
