//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.04 at 05:24:23 PM EDT 
//


package org.w3._2000._09.xmldsig_;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for X509Data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="X509Data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}X509IssuerSerial"/>
 *           &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}X509SKI"/>
 *           &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}X509SubjectName"/>
 *           &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}X509Certificate"/>
 *           &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}X509CRL"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "X509Data", namespace = "http://www.w3.org/2000/09/xmldsig#", propOrder = {
    "x509IssuerSerialOrX509SKIOrX509SubjectName"
})
public class X509Data {

    @XmlElements({
        @XmlElement(name = "X509IssuerSerial", namespace = "http://www.w3.org/2000/09/xmldsig#", type = X509IssuerSerial.class),
        @XmlElement(name = "X509SKI", namespace = "http://www.w3.org/2000/09/xmldsig#", type = X509SKI.class),
        @XmlElement(name = "X509SubjectName", namespace = "http://www.w3.org/2000/09/xmldsig#", type = X509SubjectName.class),
        @XmlElement(name = "X509Certificate", namespace = "http://www.w3.org/2000/09/xmldsig#", type = X509Certificate.class),
        @XmlElement(name = "X509CRL", namespace = "http://www.w3.org/2000/09/xmldsig#", type = X509CRL.class)
    })
    protected List<java.lang.Object> x509IssuerSerialOrX509SKIOrX509SubjectName;

    /**
     * Gets the value of the x509IssuerSerialOrX509SKIOrX509SubjectName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the x509IssuerSerialOrX509SKIOrX509SubjectName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getX509IssuerSerialOrX509SKIOrX509SubjectName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link X509IssuerSerial }
     * {@link X509SKI }
     * {@link X509SubjectName }
     * {@link X509Certificate }
     * {@link X509CRL }
     * 
     * 
     */
    public List<java.lang.Object> getX509IssuerSerialOrX509SKIOrX509SubjectName() {
        if (x509IssuerSerialOrX509SKIOrX509SubjectName == null) {
            x509IssuerSerialOrX509SKIOrX509SubjectName = new ArrayList<java.lang.Object>();
        }
        return this.x509IssuerSerialOrX509SKIOrX509SubjectName;
    }

}
